### ISSUE TITLE
[Source compatibility suite] swift compiler hanging when attempting to build Doggie in release

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#64319] opened 2023-03-13 17:30 UTC
**Describe the bug**
Doggie is failing to build its release configuration and timing out during the build process. The build appears to be hanging when attempting to compile

From the build logs you can see 
```
swift-main-source-compat-suite/build/compat_macos/install/toolchain/usr/bin/swiftc -module-name DoggieGraphics -incremental -emit-dependencies <ARGS>
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
Apple Swift version 5.9-dev (LLVM 464be04748d9067, Swift 8862b1bfb5bfab5)
Target: x86_64-apple-macosx10.13
swift-main-source-compat-suite/build/compat_macos/install/toolchain/usr/bin/swift-frontend -frontend -c <ARGS>
sandbox-exec: Timed out
```

Note that this timeout only occurs when building the tests in release config (not debug). This only occurs on main and not on 5.8. This timeout first occurred march 9th with revision: 
```
Apple Swift version 5.9-dev (LLVM 670b79bf9ad7960, Swift ac134e43815e5d5)
Target: x86_64-apple-macosx10.13
``` 

**Expected behavior**
Expecting the project to build correctly

**Environment**
```
Apple Swift version 5.9-dev (LLVM 464be04748d9067, Swift 8862b1bfb5bfab5)
Target: x86_64-apple-macosx10.13
```
https://ci.swift.org/job/swift-main-source-compat-suite/361/

**Comment by eeckstein** [comment] 2023-03-27 12:08
Should be fixed by https://github.com/apple/swift/pull/64635.

The problem is that `@inline(__always)` is put on recursive functions, which is a bad idea.
It blows up the SIL and creates enormously large functions.

**Closed** 2023-03-28 18:00 UTC
Labels: bug, compiler, optimized only, regression, source compatibility suite, swift 5.9, hang
