### ISSUE TITLE
`if` expression and `as?` generates strange error.

### ISSUE THREAD

**Issue by zienag** [apple/swift#69764] opened 2023-11-09 23:16 UTC
**Description**
If there is an `as?` expression in `if` expression, compiler complains about some `'<unknown>'` variable, that is captured before initialization

**Steps to reproduce**
code:
```
func f(x: Any?) -> Int? {
  if let x {
    x as? Int
  } else {
    0
  }
}
```
error:
```
test.swift:5:7: error: variable '<unknown>' captured by a closure before being initialized
    x as? Int
      ^
test.swift:5:7: note: variable defined here
    x as? Int
      ^
```
Workaround is to add `return` keyword or extract casting to function.

**Expected behavior**
Works like with `return` keyword

**Environment**
- Swift compiler version info 
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx13.0
- Xcode version info
Xcode 15.0
Build version 15A240d
- Deployment target: macOS 10.13

**Comment by hamishknight** [comment] 2023-11-10 10:34
Duplicate of #68764

**Closed by hamishknight** 2023-11-10 10:34 UTC
Labels: bug, triage needed
