### ISSUE TITLE
@MainActor on protocols with associated types causes compiler error: Circular reference

### ISSUE THREAD

**Issue by MaximBazarov** [apple/swift#61602] opened 2022-10-17 16:54 UTC
**Describe the bug**
This code produces the compiler error: Circular reference, 
```swift
@MainActor protocol ProtocolWithAssociatedTypes {
    associatedtype ID: Hashable
    associatedtype Value

    subscript(_ id: ID) -> Value { get set }
}

final class ClassConforming<ID: Hashable,Value>: ProtocolWithAssociatedTypes {
    subscript(id: ID) -> Value {
        get { fatalError() }
        set { fatalError() }
    }
}
```
removing `@MainActor` makes it compile 
```swift
protocol ProtocolWithAssociatedTypes {
```

**Steps To Reproduce**
1. type the code from above
2. swift build

**Expected behavior**
Should not be an error

**Screenshots**
```
Building for debugging...
/Generic_MainActor_Bug.swift:9:5: error: circular reference
    subscript(id: ID) -> Value {
    ^
/Generic_MainActor_Bug.swift:8:13: note: through reference here
final class ClassConforming<ID: Hashable,Value>: ProtocolWithAssociatedTypes {
            ^
/Generic_MainActor_Bug.swift:9:5: error: circular reference
    subscript(id: ID) -> Value {
    ^
/Generic_MainActor_Bug.swift:8:13: note: through reference here
final class ClassConforming<ID: Hashable,Value>: ProtocolWithAssociatedTypes {
```

**Environment (please fill out the following information)**
 - OS: macOS 13.0
 - ```swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.134.3 clang-1400.0.29.51)```
 - ```swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)```

**Additional Info**

removing `subscript` also compiles
```swift
@MainActor protocol ProtocolWithAssociatedTypes {
    associatedtype ID: Hashable
    associatedtype Value

    func getValue(id: ID) -> Value
    func setValue(_ value: Value, id: ID)
}

@MainActor final class ClassConforming<ID: Hashable,Value>: ProtocolWithAssociatedTypes {
    func getValue(id: ID) -> Value {
        fatalError()
    }

    func setValue(_ value: Value, id: ID) {
        fatalError()
    }
}
```

**Comment by LucianoPAlmeida** [comment] 2022-10-18 01:58
Looks like this reproduces since 5.6 and also on a near main snapshot
Swift version 5.8-dev (LLVM b9ce35da9a19288, Swift 7335d60c50dc6af)

**Comment by LucianoPAlmeida** [comment] 2022-10-18 02:32
Looks like the issue is due a cycle in `ActorIsolationRequest::evaluate` which is the reason for it only happens when `@MainActor` is involved.

**Comment by LucianoPAlmeida** [comment] 2022-10-18 03:16
Also, note that the cycle only happen with `subscript` due to specific way that `ActorIsolationRequest::evaluate` checks `AccessorDecl`.

**Comment by slavapestov** [comment] 2022-10-24 17:47
rdar://101243966

**Comment by DougGregor** [comment] 2022-10-27 00:56
I have a fix for this

**Comment by LucianoPAlmeida** [comment] 2022-10-27 00:58
Ah awesome, thanks @DougGregor =] 
Sorry I assigned but wasn't able to look at it.

**Closed** 2022-10-27 14:39 UTC
Labels: bug, ProtocolConformance, circular reference
