### ISSUE TITLE
Property wrapper parameter with projected value crashes compiler

### ISSUE THREAD

**Issue by hamishknight** [apple/swift#61223] opened 2022-09-21 12:47 UTC
The following crashes:

```swift
struct Projection<T> {
  var wrappedValue: T
}

@propertyWrapper
struct Wrapper<T> {
  var wrappedValue: T

  var projectedValue: Projection<T> {
    Projection(wrappedValue: wrappedValue)
  }
  init(projectedValue: Projection<T>) {
    self.wrappedValue = projectedValue.wrappedValue
  }
}

struct S {
  init(@Wrapper x: Int) {}
}
S(x: 0)
```

```
Assertion failed: (Index < Length && "Invalid index!"), function operator[], file ArrayRef.h, line 256.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: ./swift -frontend -typecheck /Users/hamish/src/swift-test-arena/swift-test-arena/main.swift -sdk /Users/hamish/src/MacOSX.sdk/ -debug-diagnostic-names -enable-bare-slash-regex -disable-availability-checking
1.	Swift version 5.8-dev (LLVM c205842748e1789, Swift 49c683ba4a4d115)
2.	Compiling with the current language version
3.	While evaluating request TypeCheckSourceFileRequest(source_file "/Users/hamish/src/swift-test-arena/swift-test-arena/main.swift")
4.	While type-checking statement at [/Users/hamish/src/swift-test-arena/swift-test-arena/main.swift:978:1 - line:978:7] RangeText="S(x: 0"
5.	While type-checking expression at [/Users/hamish/src/swift-test-arena/swift-test-arena/main.swift:978:1 - line:978:7] RangeText="S(x: 0"
6.	While type-checking-target starting at /Users/hamish/src/swift-test-arena/swift-test-arena/main.swift:978:1
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010bfd2607 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 39
1  swift-frontend           0x000000010bfd15d8 llvm::sys::RunSignalHandlers() + 248
2  swift-frontend           0x000000010bfd2c60 SignalHandler(int) + 288
3  libsystem_platform.dylib 0x00007ff813879dfd _sigtramp + 29
4  libsystem_platform.dylib 000000000000000000 _sigtramp + 18446603370253279776
5  libsystem_c.dylib        0x00007ff8137afd24 abort + 123
6  libsystem_c.dylib        0x00007ff8137af0cb err + 0
7  swift-frontend           0x000000010c39bfc3 (anonymous namespace)::ExprRewriter::coerceCallArguments(swift::ArgumentList*, swift::AnyFunctionType*, swift::ConcreteDeclRef, swift::ApplyExpr*, swift::constraints::ConstraintLocatorBuilder, llvm::ArrayRef<swift::AppliedPropertyWrapper>) (.cold.50) + 35
8  swift-frontend           0x00000001077ef398 (anonymous namespace)::ExprRewriter::coerceCallArguments(swift::ArgumentList*, swift::AnyFunctionType*, swift::ConcreteDeclRef, swift::ApplyExpr*, swift::constraints::ConstraintLocatorBuilder, llvm::ArrayRef<swift::AppliedPropertyWrapper>) + 7304
9  swift-frontend           0x00000001077f5ea6 (anonymous namespace)::ExprRewriter::finishApply(swift::ApplyExpr*, swift::Type, swift::constraints::ConstraintLocatorBuilder, swift::constraints::ConstraintLocatorBuilder) + 5606
10 swift-frontend           0x00000001077f7017 (anonymous namespace)::ExprRewriter::finishApply(swift::ApplyExpr*, swift::Type, swift::constraints::ConstraintLocatorBuilder, swift::constraints::ConstraintLocatorBuilder) + 10071
11 swift-frontend           0x00000001077fb5bf (anonymous namespace)::ExprRewriter::visitApplyExpr(swift::ApplyExpr*) + 287
12 swift-frontend           0x00000001077e274f (anonymous namespace)::ExprWalker::walkToExprPost(swift::Expr*) + 31
13 swift-frontend           0x0000000107e6d7d9 (anonymous namespace)::Traversal::doIt(swift::Expr*) + 137
14 swift-frontend           0x0000000107e6d73b swift::Expr::walk(swift::ASTWalker&) + 27
15 swift-frontend           0x00000001077da4fc (anonymous namespace)::ExprWalker::rewriteTarget(swift::constraints::SolutionApplicationTarget) + 492
16 swift-frontend           0x00000001077d9e90 swift::constraints::ConstraintSystem::applySolution(swift::constraints::Solution&, swift::constraints::SolutionApplicationTarget) + 896
17 swift-frontend           0x00000001079e967a swift::TypeChecker::typeCheckTarget(swift::constraints::SolutionApplicationTarget&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 394
18 swift-frontend           0x00000001079e9497 swift::TypeChecker::typeCheckExpression(swift::constraints::SolutionApplicationTarget&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 183
19 swift-frontend           0x00000001079e936e swift::TypeChecker::typeCheckExpression(swift::Expr*&, swift::DeclContext*, swift::constraints::ContextualTypeInfo, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 78
20 swift-frontend           0x0000000107abdd3f (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) + 239
21 swift-frontend           0x0000000107ac01cc swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 284
22 swift-frontend           0x0000000107abf2d3 bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 131
23 swift-frontend           0x0000000107abf362 swift::TypeChecker::typeCheckTopLevelCodeDecl(swift::TopLevelCodeDecl*) + 50
24 swift-frontend           0x0000000107af5bd6 swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 230
25 swift-frontend           0x0000000107af7d31 llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest>(swift::TypeCheckSourceFileRequest const&) + 401
26 swift-frontend           0x0000000107af7ad7 llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckSourceFileRequest, (void*)0>(swift::TypeCheckSourceFileRequest const&) + 55
27 swift-frontend           0x0000000107af5a1f swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType) + 31
28 swift-frontend           0x0000000106ca575c bool llvm::function_ref<bool (swift::SourceFile&)>::callback_fn<swift::CompilerInstance::performSema()::$_7>(long, swift::SourceFile&) + 12
29 swift-frontend           0x0000000106ca048e swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<bool (swift::SourceFile&)>) + 174
30 swift-frontend           0x0000000106ca03bb swift::CompilerInstance::performSema() + 75
31 swift-frontend           0x0000000106c37b58 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 4952
32 swift-frontend           0x0000000106a78ba6 swift::mainEntry(int, char const**) + 2278
33 dyld                     0x000000011a8d052e start + 462
fish: Job 1, './swift -frontend -typecheck /U…' terminated by signal SIGABRT (Abort)
```

rdar://100220156

**Comment by theblixguy** [comment] 2022-09-21 14:13
Looks like a duplicate of https://github.com/apple/swift/issues/60825 (this has the same crash log on main)

**Comment by hamishknight** [comment] 2022-09-21 14:15
Ah thanks @theblixguy

**Comment by theblixguy** [comment] 2022-09-21 14:17
Duplicate of #60825

**Closed by theblixguy** 2022-09-21 14:17 UTC
Labels: bug, TypeChecker, compiler crash
