### ISSUE TITLE
Segment Fault: 11 when compiling a code that uses KeyPath on a protocol's extension with a computed value

### ISSUE THREAD

**Issue by xiangyu-sun** [apple/swift#61600] opened 2022-10-17 12:31 UTC
**Describe the bug**
Swift compiler report Segment Fault: 11 when compiling a code that uses KeyPath in a map function upon a protocol's extension with a computed value.

**Steps To Reproduce**
1. in Module A,  exposes the protocols extension as public, at the same time, this protocol extension should have a computed var
```swift
public protocol TestProtcol {
  var value: Int { get set }
}

public  class TestObject: TestProtcol {
  public  var value: Int = 1
}
```
2. in another module that imports this module A, and create an array of type of protocol then map this array to extra the value
```swift
let arrayofTestProtcol: [TestProtcol] = [TestObject()]

arrayofTestProtcol.map(\.value)
```

**Expected behavior**
extracting value using `map` with a KeyPath operator on an existential object should not produce a compiler error

**Screenshots**

**Environment (please fill out the following information)**
 - OS: macOS 12.6
 - Xcode Version 14.0.1 and 13.4.1
 - swift 5.6

**Additional context**

Logs
```
 While evaluating request IRGenRequest(IR Generation for file "XXXXXXX.swift")
 While emitting IR SIL function "@$s5 XXXXXXX 14MyModelC21trackCarouselProducts04viewD4Data19storeLayoutTracking06scrollC011collectionsyAC0I0V_0B00bkL8Protocol_pSgSo08UIScrollC0CSayAA0f10CollectionC8CellTypeOGtF".
 for 'trackCarouselProducts(viewModelData:storeLayoutTracking:scrollView:collections:)' (at XXXXXXX.swift)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010931f078 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x000000010931e08c llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x000000010931f708 SignalHandler(int) + 344
3  libsystem_platform.dylib 0x00000001bcc8b4a4 _sigtramp + 56
4  swift-frontend           0x0000000105c14d78 swift::Mangle::ASTMangler::appendAnyProtocolConformance(swift::GenericSignature, swift::CanType, swift::ProtocolConformanceRef) + 468
5  swift-frontend           0x0000000105c14d78 swift::Mangle::ASTMangler::appendAnyProtocolConformance(swift::GenericSignature, swift::CanType, swift::ProtocolConformanceRef) + 468
6  swift-frontend           0x0000000105085c50 swift::irgen::IRGenMangler::mangleSymbolNameForMangledConformanceAccessorString(char const*, swift::CanGenericSignature, swift::CanType, swift::ProtocolConformanceRef) + 232
7  swift-frontend           0x0000000105026644 swift::irgen::IRGenModule::emitWitnessTableRefString(swift::CanType, swift::ProtocolConformanceRef, swift::GenericSignature, bool) + 420
8  swift-frontend           0x0000000104fe7440 void llvm::function_ref<void (swift::irgen::GenericRequirement)>::callback_fn<emitKeyPathComponent(swift::irgen::IRGenModule&, swift::irgen::ConstantStructBuilder&, swift::KeyPathPatternComponent const&, bool, swift::GenericEnvironment*, llvm::ArrayRef<swift::irgen::GenericRequirement>, swift::CanType, llvm::ArrayRef<KeyPathIndexOperand>, bool)::$_5>(long, swift::irgen::GenericRequirement) + 260
9  swift-frontend           0x000000010501774c swift::irgen::enumerateGenericSignatureRequirements(swift::CanGenericSignature, llvm::function_ref<void (swift::irgen::GenericRequirement)> const&) + 380
10 swift-frontend           0x0000000104fe217c emitKeyPathComponent(swift::irgen::IRGenModule&, swift::irgen::ConstantStructBuilder&, swift::KeyPathPatternComponent const&, bool, swift::GenericEnvironment*, llvm::ArrayRef<swift::irgen::GenericRequirement>, swift::CanType, llvm::ArrayRef<KeyPathIndexOperand>, bool) + 1200
11 swift-frontend           0x0000000104fe1688 swift::irgen::IRGenModule::getAddrOfKeyPathPattern(swift::KeyPathPattern*, swift::SILLocation) + 2000
12 swift-frontend           0x0000000105098128 swift::SILInstructionVisitor<(anonymous namespace)::IRGenSILFunction, void>::visit(swift::SILInstruction*) + 2356
13 swift-frontend           0x000000010509290c swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 8532
14 swift-frontend           0x0000000104f67288 swift::irgen::IRGenerator::emitGlobalTopLevel(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) + 1560
15 swift-frontend           0x00000001050632d4 swift::IRGenRequest::evaluate(swift::Evaluator&, swift::IRGenDescriptor) const + 7140
16 swift-frontend           0x00000001050904ec swift::SimpleRequest<swift::IRGenRequest, swift::GeneratedModule (swift::IRGenDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::IRGenRequest const&, swift::Evaluator&) + 188
17 swift-frontend           0x000000010506deb4 llvm::Expected<swift::IRGenRequest::OutputType> swift::Evaluator::getResultUncached<swift::IRGenRequest>(swift::IRGenRequest const&) + 736
18 swift-frontend           0x0000000105067ea4 swift::performIRGeneration(swift::FileUnit*, swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::StringRef, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::GlobalVariable**) + 236
19 swift-frontend           0x0000000104bcd3f4 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 2524
20 swift-frontend           0x0000000104bc0acc swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 5344
21 swift-frontend           0x0000000104b883c4 swift::mainEntry(int, char const**) + 808
22 dyld                     0x000000010baf108c start + 520
error: Segmentation fault: 11 (in target 'XXXXXXX' from project 'XXXXXXX')
```

**Comment by AnthonyLatsis** [comment] 2022-10-18 03:42
Duplicate of #58289

**Closed by AnthonyLatsis** 2022-10-18 03:42 UTC
Labels: bug, duplicate, compiler, compiler crash, SILGen, key paths, crash, existentials, swift 5.6
