### ISSUE TITLE
Xcode-beta (15.0) C++ interop option generates erroneous 'let' property initialization code

### ISSUE THREAD

**Issue by ByunghoonKim** [apple/swift#66523] opened 2023-06-10 01:04 UTC
**Description**

**Steps to reproduce**
1) Install Xcode 15.0 beta (15A5160n). Create a new **macOS** app project. Placeholder code compiles well.
2) set Xcode > Settings > Command Line Tools: **Xcode-beta 15.0 (15A5160n)** 
3) choose Project > Build Settings > Swift Compiler - Language > **C++/Objective-C++**, and build
4) Build fails

**Expected behavior**
Compile & Run

<img width="1512" alt="Screenshot 2023-06-10 at 9 57 53" src="https://github.com/apple/swift/assets/44054076/6430171b-dae8-47e7-bb07-2069eeaeb06a">

**Environment**
- Swift compiler version info 
```
swift-driver version: 1.82.2 Apple Swift version 5.9 (swiftlang-5.9.0.114.6 clang-1500.0.27.1)
Target: arm64-apple-macosx13.0
```
- Xcode version info
```
Xcode 15.0
Build version 15A5160n
```
- Deployment target: 
```
macOS 13.4
```

**Comment by hyp** [comment] 2023-06-13 18:54
@egorzhdan  are you looking into this one?

**Comment by egorzhdan** [comment] 2023-06-20 16:15
I cannot reproduce this with a newly created macOS App project.
@ByunghoonKim could you please elaborate on how you are creating the project in Xcode?

**Comment by ByunghoonKim** [comment] 2023-06-21 01:58
I have done nothing special other than what I described in the original post.

I am working on a 2021 MacBook Pro (M1 Pro) with Ventura 13.4. To be sure, I have deleted both Xcode 14 and Xcode 15 beta, re-installed Xcode 15 beta, and rebooted my laptop twice just now.
This is what happens. (sorry for the movie quality. had to make it under 10MB)


https://github.com/apple/swift/assets/44054076/bccf27d1-9600-4059-ada8-670a0a76ac81

**Comment by ByunghoonKim** [comment] 2023-07-06 10:08
Hi, 
I am here to report that the issue I described above has disappeared with Xcode 15 beta 3. The erroneous code generation has, however, continued to be problematic with beta 2.

Because I see no pull request regarding this issue, I do not know if the underlying problem, if any, is actively resolved, or it was mere a symptom of something else that has been patched with beta 3. In any case, since my problem is gone, I'd like to ask if it would be helpful for your workflow if I closed this issue.

Thank you for the update, anyway. :)

**Comment by egorzhdan** [comment] 2023-07-06 11:20
Thanks @ByunghoonKim for the update! Glad to know this is no longer an issue for you.

Unfortunately the underlying issue is not yet fixed, we're tracking it as rdar://110431818 internally.

**Comment by ByunghoonKim** [comment] 2023-07-06 13:35
If that is the case, I will leave it open for now. Thanks again for the effort, @egorzhdan.

**Comment by hyp** [comment] 2023-07-11 17:25
I will close this issue since it does not reproduce with Beta 3 anymore. If this reoccurs we can reopen it.

**Closed by hyp** 2023-07-11 17:25 UTC
Labels: bug, c++ interop, triage needed
