### ISSUE TITLE
SIL verification failure: keypath value type should match value type of keypath pattern

### ISSUE THREAD

**Issue by fibrechannelscsi** [apple/swift#71569] opened 2024-02-13 00:23 UTC
### Description

The code below crashes the compiler when an attempt is made to run it in a unit test environment, either via Xcode or on the command line via `swift test`.

### Reproduction

Copy and paste the below code into a unit test framework where `XCTest` is available.
```swift
import Foundation; import XCTest
final class H: XCTestCase {func testA() throws {let a:[Double?] = []; let p = S<Double, Double>(a).w(); XCTAssertEqual(p.map(\.v), [0].map {a[$0]})}}
struct S<B: E, D> {init(_ d: [D?] = []) {}; func w() -> [(i: B, v: D)] {fatalError()}}
protocol E{}; extension Double:E{}
```

Any `main` files associated with the project can be empty. No specific dependencies outside of `Foundation` and `XCTest` are needed.

Attempt to run the unit test case containing `testA()` above.

### Expected behavior

The unit test should compile successfully, and upon running, should hit the `fatalError()` call in `w()`. 

### Environment

Nightly toolchains 2024-02-04a and 2024-02-11a on an M1 exhibit this issue.
Toolchain 2024-01-30a compiles this successfully, however. 

### Additional information

The SIL verification error message looks like this:
```
SIL verification failed: keypath value type should match value type of keypath pattern
  Optional<Double>
  Double
Verifying instruction:
->   %6 = keypath $KeyPath<(i: Double, v: Double), Optional<Double>>, (root $(i: Double, v: Double); tuple_element #1 : $Double) // user: %7
     %7 = move_value [lexical] [var_decl] %6 : $KeyPath<(i: Double, v: Double), Optional<Double>> // users: %13, %9
In function:
// implicit closure #1 in H.testA()
sil private [transparent] [ossa] @$s16kpTests1HC5testAyyKFSaySdSgGyKXEfu_ : $@convention(thin) @substituted <τ_0_0> (@guaranteed Array<(i: Double, v: Double)>) -> (@out τ_0_0, @error any Error) for <Array<Optional<Double>>> {
// %0 "$return_value"                             // user: %22
// %1 "p"                                         // users: %5, %3
bb0(%0 : $*Array<Optional<Double>>, %1 : @closureCapture @guaranteed $Array<(i: Double, v: Double)>):
  debug_value undef : $any Error, var, name "$error", argno 1 // id: %2
  debug_value %1 : $Array<(i: Double, v: Double)>, let, name "p", argno 2 // id: %3
  %4 = alloc_stack $Array<(i: Double, v: Double)> // users: %21, %5
  %5 = store_borrow %1 to %4 : $*Array<(i: Double, v: Double)> // users: %20, %16
  %6 = keypath $KeyPath<(i: Double, v: Double), Optional<Double>>, (root $(i: Double, v: Double); tuple_element #1 : $Double) // user: %7
  %7 = move_value [lexical] [var_decl] %6 : $KeyPath<(i: Double, v: Double), Optional<Double>> // users: %13, %9
  // function_ref implicit closure #2 in implicit closure #1 in H.testA()
  %8 = function_ref @$s16kpTests1HC5testAyyKFSaySdSgGyKXEfu_AESd1i_Sd1vt_tcfu0_ : $@convention(thin) @substituted <τ_0_0, τ_0_1, τ_0_2> (@in_guaranteed τ_0_0, @guaranteed KeyPath<(i: Double, v: Double), Optional<Double>>) -> (@out τ_0_2, @error_indirect τ_0_1) for <(i: Double, v: Double), Never, Optional<Double>> // user: %10
  %9 = copy_value %7 : $KeyPath<(i: Double, v: Double), Optional<Double>> // user: %10
  %10 = partial_apply [callee_guaranteed] %8(%9) : $@convention(thin) @substituted <τ_0_0, τ_0_1, τ_0_2> (@in_guaranteed τ_0_0, @guaranteed KeyPath<(i: Double, v: Double), Optional<Double>>) -> (@out τ_0_2, @error_indirect τ_0_1) for <(i: Double, v: Double), Never, Optional<Double>> // users: %12, %11
  %11 = convert_escape_to_noescape [not_guaranteed] %10 : $@callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2> (@in_guaranteed τ_0_0) -> (@out τ_0_2, @error_indirect τ_0_1) for <(i: Double, v: Double), Never, Optional<Double>> to $@noescape @callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2> (@in_guaranteed τ_0_0) -> (@out τ_0_2, @error_indirect τ_0_1) for <(i: Double, v: Double), Never, Optional<Double>> // users: %19, %16
  destroy_value %10 : $@callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2> (@in_guaranteed τ_0_0) -> (@out τ_0_2, @error_indirect τ_0_1) for <(i: Double, v: Double), Never, Optional<Double>> // id: %12
  destroy_value %7 : $KeyPath<(i: Double, v: Double), Optional<Double>> // id: %13
  // function_ref Collection.map<A, B>(_:)
  %14 = function_ref @$sSlsE3mapySayqd__Gqd__7ElementQzqd_0_YKXEqd_0_YKs5ErrorRd_0_r0_lF : $@convention(method) <τ_0_0 where τ_0_0 : Collection><τ_1_0, τ_1_1 where τ_1_1 : Error> (@guaranteed @noescape @callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2> (@in_guaranteed τ_0_0) -> (@out τ_0_2, @error_indirect τ_0_1) for <τ_0_0.Element, τ_1_1, τ_1_0>, @in_guaranteed τ_0_0) -> (@owned Array<τ_1_0>, @error_indirect τ_1_1) // user: %16
  %15 = alloc_stack $Never                        // users: %18, %16
  try_apply %14<[(i: Double, v: Double)], Double?, Never>(%15, %11, %5) : $@convention(method) <τ_0_0 where τ_0_0 : Collection><τ_1_0, τ_1_1 where τ_1_1 : Error> (@guaranteed @noescape @callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2> (@in_guaranteed τ_0_0) -> (@out τ_0_2, @error_indirect τ_0_1) for <τ_0_0.Element, τ_1_1, τ_1_0>, @in_guaranteed τ_0_0) -> (@owned Array<τ_1_0>, @error_indirect τ_1_1), normal bb1, error bb2 // id: %16

// %17                                            // user: %22
bb1(%17 : @owned $Array<Optional<Double>>):       // Preds: bb0
  dealloc_stack %15 : $*Never                     // id: %18
  destroy_value %11 : $@noescape @callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2> (@in_guaranteed τ_0_0) -> (@out τ_0_2, @error_indirect τ_0_1) for <(i: Double, v: Double), Never, Optional<Double>> // id: %19
  end_borrow %5 : $*Array<(i: Double, v: Double)> // id: %20
  dealloc_stack %4 : $*Array<(i: Double, v: Double)> // id: %21
  store %17 to [init] %0 : $*Array<Optional<Double>> // id: %22
  %23 = tuple ()                                  // user: %24
  return %23 : $()                                // id: %24

bb2:                                              // Preds: bb0
  unreachable                                     // id: %25
} // end sil function '$s16kpTests1HC5testAyyKFSaySdSgGyKXEfu_'
```

The stack trace looks like this:
```
1.  Apple Swift version 5.11-dev (LLVM 9c1871861fb62d4, Swift 2fa1022a912a1c0)
2.  Compiling with the current language version
3.  While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "/Users/user/playground/kp/Tests/kpTests/kpTests.swift")
4.  While silgen emitFunction SIL function "@$s16kpTests1HC5testAyyKF".
 for 'testA()' (at /Users/user/playground/kp/Tests/kpTests/kpTests.swift:2:28)
5.  While silgen closureexpr SIL function "@$s16kpTests1HC5testAyyKFSaySdSgGyKXEfu_".
 for expression at [/Users/user/playground/kp/Tests/kpTests/kpTests.swift:2:120 - line:2:129] RangeText="p.map(\.v"
6.  While verifying SIL function "@$s16kpTests1HC5testAyyKFSaySdSgGyKXEfu_".
 for expression at [/Users/user/playground/kp/Tests/kpTests/kpTests.swift:2:120 - line:2:129] RangeText="p.map(\.v"
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x00000001059d9a7c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x00000001059d8248 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x00000001059da0c4 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000018b12aa24 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000018b0fbc28 pthread_kill + 288
5  libsystem_c.dylib        0x000000018b009ae8 abort + 180
6  swift-frontend           0x00000001014b8f78 swift::SILOptions::~SILOptions() + 0
7  swift-frontend           0x00000001014cbd0c swift::SILVisitorBase<(anonymous namespace)::SILVerifier, void>::visitSILBasicBlock(swift::SILBasicBlock*) + 60404
8  swift-frontend           0x00000001014bd018 (anonymous namespace)::SILVerifier::visitSILBasicBlock(swift::SILBasicBlock*) + 28
9  swift-frontend           0x00000001014bbaf8 (anonymous namespace)::SILVerifier::visitSILFunction(swift::SILFunction*) + 9800
10 swift-frontend           0x00000001014b5504 swift::SILFunction::verify(swift::CalleeCache*, bool, bool, bool) const + 204
11 swift-frontend           0x0000000100b91d54 swift::Lowering::SILGenModule::postEmitFunction(swift::SILDeclRef, swift::SILFunction*) + 256
12 swift-frontend           0x0000000100b91600 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 6268
13 swift-frontend           0x0000000100b931ec swift::Lowering::SILGenModule::emitClosure(swift::AbstractClosureExpr*) + 188
14 swift-frontend           0x0000000100c10b08 (anonymous namespace)::RValueEmitter::visitAbstractClosureExpr(swift::AbstractClosureExpr*, swift::Lowering::SGFContext) + 368
15 swift-frontend           0x0000000100bf98c0 swift::Lowering::SILGenFunction::emitRValueAsSingleValue(swift::Expr*, swift::Lowering::SGFContext) + 56
16 swift-frontend           0x0000000100bdfa78 swift::Lowering::SILGenFunction::emitConvertedRValue(swift::SILLocation, swift::Lowering::Conversion const&, swift::Lowering::SGFContext, llvm::function_ref<swift::Lowering::ManagedValue (swift::Lowering::SILGenFunction&, swift::SILLocation, swift::Lowering::SGFContext)>) + 268
17 swift-frontend           0x0000000100b7897c swift::Lowering::ArgumentSource::getConverted(swift::Lowering::SILGenFunction&, swift::Lowering::Conversion const&, swift::Lowering::SGFContext) && + 184
18 swift-frontend           0x0000000100bb06b0 (anonymous namespace)::ArgEmitter::emit(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, std::__1::optional<swift::AnyFunctionType::Param>) + 3840
19 swift-frontend           0x0000000100ba1de4 (anonymous namespace)::ArgEmitter::emitSingleArg(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, std::__1::optional<swift::AnyFunctionType::Param>) + 416
20 swift-frontend           0x0000000100baecd4 (anonymous namespace)::ArgEmitter::emitPreparedArgs(swift::Lowering::PreparedArguments&&, swift::Lowering::AbstractionPattern) + 192
21 swift-frontend           0x0000000100bb99e8 (anonymous namespace)::CallSite::emit(swift::Lowering::SILGenFunction&, swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, (anonymous namespace)::ParamLowering&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, llvm::SmallVectorImpl<(anonymous namespace)::DelayedArgument>&, swift::ForeignInfo const&) && + 536
22 swift-frontend           0x0000000100bb93b0 (anonymous namespace)::CallEmission::emitArgumentsForNormalApply(swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, swift::ForeignInfo const&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, std::__1::optional<swift::SILLocation>&) + 1060
23 swift-frontend           0x0000000100ba4f30 (anonymous namespace)::CallEmission::apply(swift::Lowering::SGFContext) + 2076
24 swift-frontend           0x0000000100ba34ac swift::Lowering::SILGenFunction::emitApplyExpr(swift::ApplyExpr*, swift::Lowering::SGFContext) + 2028
25 swift-frontend           0x0000000100bf9e98 swift::Lowering::SILGenFunction::emitIgnoredExpr(swift::Expr*) + 912
26 swift-frontend           0x0000000100c7a678 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 4316
27 swift-frontend           0x0000000100c79590 swift::Lowering::SILGenFunction::emitStmt(swift::Stmt*) + 24
28 swift-frontend           0x0000000100c1af48 swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 460
29 swift-frontend           0x0000000100b915d8 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 6228
30 swift-frontend           0x0000000100b922b0 swift::Lowering::SILGenModule::emitOrDelayFunction(swift::SILDeclRef) + 220
31 swift-frontend           0x0000000100b8fd4c swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 196
32 swift-frontend           0x0000000100c8d97c (anonymous namespace)::SILGenType::visitFuncDecl(swift::FuncDecl*) + 28
33 swift-frontend           0x0000000100c8aa38 (anonymous namespace)::SILGenType::emitType() + 220
34 swift-frontend           0x0000000100c8a950 swift::Lowering::SILGenModule::visitNominalTypeDecl(swift::NominalTypeDecl*) + 24
35 swift-frontend           0x0000000100b94c44 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 988
36 swift-frontend           0x0000000100c78fe8 swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 148
37 swift-frontend           0x0000000100b9ac48 llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 396
38 swift-frontend           0x0000000100b955ac swift::performASTLowering(swift::FileUnit&, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) + 92
39 swift-frontend           0x000000010059a0e0 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 580
40 swift-frontend           0x00000001005aacf0 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
41 swift-frontend           0x000000010059c624 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 708
42 swift-frontend           0x000000010059b658 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2292
43 swift-frontend           0x00000001003ea4ac swift::mainEntry(int, char const**) + 3096
44 dyld                     0x000000018ada3f28 start + 2236
```

**Comment by xedin** [comment] 2024-02-13 00:34
Looks like a dupe of https://github.com/apple/swift/issues/71423

**Closed by xedin** 2024-02-13 00:34 UTC
Labels: bug, triage needed
