### ISSUE TITLE
`@discardableResult` is ignored when used with `try?`

### ISSUE THREAD

**Issue by StevenMagdy** [apple/swift#59956] opened 2022-07-07 23:54 UTC
**Describe the bug**
When calling a function declared with `@discardableResult` using `try?`, I receive a warning for the unused return value.

**Steps To Reproduce**
```swift
@discardableResult
func ignoreThis() throws -> String {
  return ""
}

func test() throws {
  try? ignoreThis() // Warning
  try ignoreThis() // OK
}
```

**Environment (please fill out the following information)**
 - Xcode 13.4.1

**Comment by YOCKOW** [comment] 2022-07-08 01:03
I know how you feel, but this is a duplicate of [SR-3082](https://github.com/apple/swift/issues/45672).

**Closed by YOCKOW** 2022-07-08 01:03 UTC
Labels: bug

**Comment by StevenMagdy** [comment] 2022-07-08 01:29
@YOCKOW No worries. I tried searching for a similar issue before opening a new one but I guess I ignored the duplicate because the title is not very clear.
