### ISSUE TITLE
[SR-15975] `swift -help` fails with 5.6 development toolchain

### ISSUE THREAD

**Issue by dabrahams** [apple/swift#58236] opened 2022-03-13 22:22 UTC
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15975      |
   |Radar             | None         |
   |Original Reporter | @dabrahams      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: dd2b807a02e39b61328573e7109f93f9

  </details>

**Issue Description:**

    $ TOOLCHAINS=org.swift.56202203021a swift -help
    dyld[16487]: Library not loaded: @rpath/libArgumentParserToolInfo.dylib
      Referenced from: /Library/Developer/Toolchains/swift-5.6-DEVELOPMENT-SNAPSHOT-2022-03-02-a.xctoolchain/usr/lib/swift/macosx/libArgumentParser.dylib
      Reason: tried: '/usr/lib/swift/libArgumentParserToolInfo.dylib' (no such file), '/Users/ec2-user/jenkins/workspace/oss-swift-5.6-package-macos/build/buildbot_osx/swiftdriver-macosx-x86_64/x86_64-apple-macosx10.15/release/dependencies/swift-argument-parser/lib/libArgumentParserToolInfo.dylib' (no such file), '/usr/lib/swift/libArgumentParserToolInfo.dylib' (no such file), '/Library/Developer/Toolchains/swift-5.6-DEVELOPMENT-SNAPSHOT-2022-03-02-a.xctoolchain/usr/bin/../lib/swift/macosx/libArgumentParserToolInfo.dylib' (no such file), '/usr/lib/swift/libArgumentParserToolInfo.dylib' (no such file), '/Library/Developer/Toolchains/swift-5.6-DEVELOPMENT-SNAPSHOT-2022-03-02-a.xctoolchain/usr/bin/../lib/swift/macosx/libArgumentParserToolInfo.dylib' (no such file), '/usr/lib/libArgumentParserToolInfo.dylib' (no such file)

**Comment by AnthonyLatsis** [comment] 2023-01-16 14:16
Closing because I cannot reproduce this a recent snapshot.

**Closed by AnthonyLatsis** 2023-01-16 14:16 UTC
Labels: bug, toolchain
