### ISSUE TITLE
Xcode squeezes the value out of diagnostics

### ISSUE THREAD

**Issue by dabrahams** [apple/swift#62644] opened 2022-12-16 19:12 UTC
When I’m compiling in emacs, I’ll see:
```
/Users/dave/src/val/Sources/FrontEnd/Parse/Parser.swift:359:22: error: 'diagnose' is inaccessible due to 'internal' protection level
          Diagnostic.diagnose(unexpectedAccessModifier:)))
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dave/src/val/Sources/Core/AST/AST+Diagnostics.swift:125:15: note: 'diagnose(unexpectedAccessModifier:)' declared here
  static func diagnose(
              ^
```
and I can click the 2nd line and jump to the file to make the func public.  

In Xcode, I get the following, with no ability to navigate to the source of the problem, and no fix-it, presumably because it’s a cross-module problem.
<img width="557" alt="image" src="https://user-images.githubusercontent.com/44065/208171224-0569fe28-f662-4ece-8e6c-af7a1c89cc41.png">

This is just one example of how working in Xcode seems to make diagnostics less valuable than they would otherwise be.

Xcode Version 14.2 (14C18)

**Comment by AnthonyLatsis** [comment] 2023-01-25 18:16
I don’t see us emitting any fix-its for this diagnostic whatsoever. I guess the motivation is that changes to access levels should be done cautiously in general.

The note clearly has a valid location, so the other problem lies with Xcode. I trust you know Xcode bugs ought to be reported to the feedback assistant?

**Comment by dabrahams** [comment] 2023-01-26 00:54
Yeah, in theory.

In practice that medium is unexpressive; IIRC I couldn't attach a screenshot, for example.  If you're not going to create an Xcode radar for it, I'll just drop it.  I hardly use Xcode at all for this exact reason, so it's not something that changes my life.  I was just trying to help the ecosystem by reporting it.

**Comment by AnthonyLatsis** [comment] 2023-01-26 03:35
@hborla I heard you worked on Xcode formerly. Do you know of anyone on GitHub we can ask to take notice of this? If not, I will try to report it next week.

**Comment by hborla** [comment] 2023-01-30 19:06
I'm closing this bug, as it's not a bug in the Swift compiler or it's diagnostics machinery. Please do file Xcode bugs using Apple's FeedbackAssistant

**Closed by hborla** 2023-01-30 19:06 UTC
Labels: bug, compiler, diagnostics QoI, xcode, access control
