### ISSUE TITLE
Swift script importing Cocoa frameworks (Cocoa, AppKit, CryptoKit) fails with Symbols not found (macOS 14)

### ISSUE THREAD

**Issue by rdj** [apple/swift#68785] opened 2023-09-27 00:50 UTC
**Description**
Swift script that imports AppKit fails with "JIT session error: Symbols not found". 

By "swift script" I mean a swift source file that is run directly with `/usr/bin/swift`, `xcrun swift`, or as an executable script with a shebang line like `#!/usr/bin/env swift`. 

Using `swiftc` on the same source file compiles cleanly and the executable works as expected.

**Steps to reproduce**
```
 $ printf 'import AppKit\n\nprint( NSScreen.main!.frame.size )' > a.swift && swift a.swift
JIT session error: Symbols not found: [ _OBJC_CLASS_$_NSScreen ]
Failed to materialize symbols: { (main, { _$sSoMXM, __swift_FORCE_LOAD_$_swiftDarwin_$_a, __swift_FORCE_LOAD_$_swiftObjectiveC_$_a, __swift_FORCE_LOAD_$_swiftDispatch_$_a, __swift_FORCE_LOAD_$_swiftXPC_$_a, _$ss5print_9separator10terminatoryypd_S2StFfA0_, _$ss27_finalizeUninitializedArrayySayxGABnlF, _got.$s12CoreGraphics7CGFloatVMn, __swift_FORCE_LOAD_$_swiftos_$_a, _symbolic _____ So6CGSizeV, _symbolic _____ 12CoreGraphics7CGFloatV, _$ss5print_9separator10terminatoryypd_S2StFfA1_, _$sSo6CGSizeVwst, __swift_FORCE_LOAD_$_swiftCoreImage_$_a, _$sSa12_endMutationyyF, __swift_FORCE_LOAD_$_swiftCoreGraphics_$_a, _$sSo6CGSizeVMF, $.a.__inits.0, __swift_FORCE_LOAD_$_swiftQuartzCore_$_a, __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_a, __swift_FORCE_LOAD_$_swiftMetal_$_a, _$sSo6CGSizeVMn, _$sSo6CGSizeVMf, __swift_FORCE_LOAD_$_swiftCoreFoundation_$_a, _$sSo6CGSizeVML, _$sSo6CGSizeVMB, __swift_FORCE_LOAD_$_swiftFoundation_$_a, _main, _$sSo6CGSizeVwet, _$sSo6CGSizeVMa, __swift_FORCE_LOAD_$_swiftOSLog_$_a, _$sSo6CGSizeVWV, ___swift_noop_void_return, ___swift_memcpy16_8, __swift_FORCE_LOAD_$_swiftIOKit_$_a }) }

 $ swiftc a.swift && ./a
(2560.0, 1440.0)
```

**Expected behavior**
Should work when run directly with `swift` or as an executable with `#!/usr/bin/env swift`. 

**Environment**
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0

Xcode 15.0
Build version 15A240d

**Related Issues**
Similar to https://github.com/apple/swift/issues/59354

**Comment by ausdrew** [comment] 2023-09-27 11:01
+1 - Sonoma has bricked my lil' command line scripts I was using fine on Ventura

Except with `import Cocoa`.

swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0

```
JIT session error: Symbols not found: [ _OBJC_CLASS_$_NSPasteboard, _NSPasteboardTypeString ]
```

**Comment by rdj** [comment] 2023-09-27 21:23
Also works as expected from REPL:

```
$ swift repl
Welcome to Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1).
Type :help for assistance.
  1> import AppKit
  2> let screenSize = NSScreen.main!.frame.size
screenSize: CGSize = (width = 2560, height = 1440)
```

**Comment by zxdposter** [comment] 2023-11-14 06:54
xcrun -sdk macosx swiftc YourScript.swift -o YourScript. [from](https://developer.apple.com/forums/thread/710274)

**Comment by tib** [comment] 2023-11-14 15:10
> @ausdrew xcrun -sdk macosx swiftc YourScript.swift -o YourScript. [from](https://developer.apple.com/forums/thread/710274), its work for me.

That command is invoking the Swift compiler and instead of running the script directly using the `swift` command. @rdj also mentioned that it's possible to compile the source file... 

Based on my experience, this issue still exists. Hopefully someone from Apple will see this and provide a fix real soon. 🤞 🙏

**Comment by skonesam** [comment] 2023-11-17 21:49
It's not just AppKit -- I have many similar little scripts that fail from importing Cocoa.

Started off as an easy way to get familiar with the language. Now that they're failing, I realize I relied on them a LOT!

**Comment by hvge** [comment] 2023-11-28 08:48
I have the same problem when script is using `CryptoKit` framework.

**Comment by dempseyatgithub** [comment] 2023-12-07 17:56
I am also seeing this issue when trying to import Core Data in a script that has worked for years.

Since this may be a macOS / Swift integration issue and not a pure Swift issue, I have filed a Feedback with Apple: 
'FB13453942 Regression: Scripts written in Swift fail when importing system frameworks'

**Comment by dempseyatgithub** [comment] 2023-12-07 18:08
@rdj Would you be able to add the 'regression' tag to this issue? Hopefully that would help raise its visibility.

**Comment by benlangmuir** [comment] 2023-12-08 22:22
This appears to be indirectly related to libswiftAppKit code being merged back into AppKit.  Before that SDK change, we would autolink libswiftAppKit.  That caused us to do:
```
dlopen("libswiftAppKit.dylib", ...)
```

that succeeds, and it pulls in AppKit.framework as a dependency.  On 14.0 and later, we autolink AppKit.framework not the overlay dylib, and call

```
dlopen("AppKit.framework/AppKit", ...)
```

which fails.  I think the right fix would be for us to actually use the path `/System/Library/Frameworks/AppKit.framewok/AppKit`.

As an aside, after the SDK change we needed the following https://github.com/apple/swift/commit/e7590072569f267bb4885657e84c591d69505899 so that running on macOS < 14.0 but building against a 14+ SDK  we get the right behaviour.  But that's not directly relevant here.

**Comment by Savjee** [comment] 2024-01-19 13:12
I found a workaround. If you manually set the system framework search path, everything works:

```
swift -Fsystem /System/Library/Frameworks path_to_script.swift
```

**Comment by jessesquires** [comment] 2024-01-19 19:08
@Savjee Hm, that does not seem to work for all use cases. I have a script that imports `Foundation` and `AppKit`

Invoking it using `-Fsystem /System/Library/Frameworks` produces the following errors:

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/AppKit.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:10:9: error: 'Foundation/Foundation.h' file not found
#import <Foundation/Foundation.h>
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:10:9: note: did not find header 'Foundation.h' in framework 'Foundation' (loaded from '/System/Library/Frameworks')
#import <Foundation/Foundation.h>
        ^
<unknown>:0: error: could not build Objective-C module 'AppKit'
```

**Comment by rdj** [comment] 2024-01-22 17:55
@lhames So should just setting the environment have the same effect, cause it does not resolve the repro from the original bug:

```
$ printf 'import AppKit\n\nprint( NSScreen.main!.frame.size )' > a.swift
$ DYLD_FRAMEWORK_PATH=/System/Library/Frameworks swift a.swift
JIT session error: Symbols not found: [ _OBJC_CLASS_$_NSScreen ]
Failed to materialize symbols: { (main, { _got.$s12CoreGraphics7CGFloatVMn, __swift_FORCE_LOAD_$_swiftCoreGraphics_$_a, _symbolic _____ 12CoreGraphics7CGFloatV, ___swift_noop_void_return, __swift_FORCE_LOAD_$_swiftMetal_$_a, _$ss5print_9separator10terminatoryypd_S2StFfA0_, __swift_FORCE_LOAD_$_swiftQuartzCore_$_a, ___swift_memcpy16_8, _$ss27_finalizeUninitializedArrayySayxGABnlF, __swift_FORCE_LOAD_$_swiftos_$_a, _$ss5print_9separator10terminatoryypd_S2StFfA1_, __swift_FORCE_LOAD_$_swiftDarwin_$_a, __swift_FORCE_LOAD_$_swiftObjectiveC_$_a, __swift_FORCE_LOAD_$_swiftDispatch_$_a, __swift_FORCE_LOAD_$_swiftXPC_$_a, _$sSo6CGSizeVMB, _$sSo6CGSizeVML, __swift_FORCE_LOAD_$_swiftCoreFoundation_$_a, $.a.__inits.0, _$sSo6CGSizeVMF, __swift_FORCE_LOAD_$_swiftFoundation_$_a, _$sSoMXM, _$sSo6CGSizeVWV, __swift_FORCE_LOAD_$_swiftOSLog_$_a, _symbolic _____ So6CGSizeV, _$sSo6CGSizeVMf, _$sSo6CGSizeVMn, __swift_FORCE_LOAD_$_swiftIOKit_$_a, _$sSo6CGSizeVwet, __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_a, _$sSa12_endMutationyyF, __swift_FORCE_LOAD_$_swiftCoreImage_$_a, _$sSo6CGSizeVMa, _$sSo6CGSizeVwst, _main }) }
```

**Comment by lhames** [comment] 2024-01-22 18:23
> @lhames So should just setting the environment have the same effect, cause it does not resolve the repro from the original bug: ...

I've been testing on top-of-tree. It's possible that there's something else going on on 5.9.

Could you try running `DYLD_PRINT_SEARCHING=1 DYLD_FRAMEWORK_PATH=/System/Library/Frameworks swift a.swift` and attach the output?

**Comment by rdj** [comment] 2024-01-22 18:55
Hmm, no effect.

Judging from `man dyld`, probably because "Note: If System Integrity Protection is enabled, these environment variables are ignored when executing binaries protected by System Integrity Protection." Which means it is *also* ignoring the DYLD_FRAMEWORK_PATH var, so maybe the fix will work.

Ok, I can get it to listen to the DYLD vars by invoking the xcode-installed `swift` directly. At which point this does seem to fix the problem: 

```
$ DYLD_FRAMEWORK_PATH=/System/Library/Frameworks /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift a.swift
(2560.0, 1440.0)
```

Oddly, it does not work through `xcrun`, but using the `-find` path does. I guess xcrun is SIP protected and it gets stripped out of the environment before calling into swift. 

```
$ DYLD_FRAMEWORK_PATH=/System/Library/Frameworks xcrun swift a.swift 
JIT session error: Symbols not found: [ _OBJC_CLASS_$_NSScreen ]
Failed to materialize symbols: { (main, { _$ss5print_9separator10terminatoryypd_S2StFfA0_, _symbolic _____ 12CoreGraphics7CGFloatV, _$ss5print_9separator10terminatoryypd_S2StFfA1_, ___swift_memcpy16_8, __swift_FORCE_LOAD_$_swiftQuartzCore_$_a, _$ss27_finalizeUninitializedArrayySayxGABnlF, _got.$s12CoreGraphics7CGFloatVMn, ___swift_noop_void_return, _$sSo6CGSizeVMB, __swift_FORCE_LOAD_$_swiftDarwin_$_a, _$sSo6CGSizeVMF, $.a.__inits.0, __swift_FORCE_LOAD_$_swiftXPC_$_a, __swift_FORCE_LOAD_$_swiftos_$_a, __swift_FORCE_LOAD_$_swiftObjectiveC_$_a, __swift_FORCE_LOAD_$_swiftCoreFoundation_$_a, _symbolic _____ So6CGSizeV, __swift_FORCE_LOAD_$_swiftIOKit_$_a, _$sSo6CGSizeVwst, __swift_FORCE_LOAD_$_swiftDispatch_$_a, _$sSa12_endMutationyyF, __swift_FORCE_LOAD_$_swiftFoundation_$_a, _$sSo6CGSizeVML, __swift_FORCE_LOAD_$_swiftCoreImage_$_a, _$sSo6CGSizeVMf, _$sSo6CGSizeVwet, _$sSo6CGSizeVMn, __swift_FORCE_LOAD_$_swiftMetal_$_a, _$sSoMXM, __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_a, _$sSo6CGSizeVWV, __swift_FORCE_LOAD_$_swiftOSLog_$_a, _$sSo6CGSizeVMa, __swift_FORCE_LOAD_$_swiftCoreGraphics_$_a, _main }) }

$ DYLD_FRAMEWORK_PATH=/System/Library/Frameworks $(xcrun -find swift) a.swift 
(2560.0, 1440.0)
```

Thank, @lhames, it does seem like this will fix the top-post repro on this issue.

**Comment by rdj** [comment] 2024-01-22 19:02
So for others on the thread, a workaround if you have xcode installed, is to change your shebang line:

```
#!/usr/bin/env DYLD_FRAMEWORK_PATH=/System/Library/Frameworks /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift
```

**Comment by lhames** [comment] 2024-01-22 19:09
@rdj Ahh. I need to do some more testing on a SIP enabled machine.

> Thank, @lhames, it does seem like this will fix the top-post repro on this issue.

I think this is a reasonable interim solution, but I'm not sure it's the _best_ solution. I'm happy to keep discussing.

**Comment by jessesquires** [comment] 2024-01-22 23:20
> So for others on the thread, a workaround — if you have xcode installed — is to change your shebang line:

@rdj thank you for this! 🙌🏼  Confirmed it works for me.

**Closed** 2024-01-25 20:03 UTC
Labels: bug, regression, triage needed, swift 5.9

**Comment by ubertao** [comment] 2024-05-09 01:04
These hashbangs worked for me:
`#!/usr/bin/env swift -Fsystem /System/Library/Frameworks`
`#!/usr/bin/swift -Fsystem /System/Library/Frameworks`
