### ISSUE TITLE
compiler crash: Invalid type parameter in getReducedType()

### ISSUE THREAD

**Issue by kelvin13** [apple/swift#61441] opened 2022-10-04 20:13 UTC
crashes on `DEVELOPMENT-SNAPSHOT-2022-09-29-a`:

```swift
struct S<T> where T
{
}
protocol Q:Collection<S<A>>
{
    associatedtype A

    subscript(index:Int) -> S<A>
    {
        get 
    }
}
```

```
$ swiftc test10.swift 
error: compile command failed due to signal 6 (use -v to see invocation)
test10.swift:2:1: error: expected ':' or '==' to indicate a conformance or same-type requirement
{
^
test10.swift:4:25: error: cannot find type 'A' in scope
protocol Q:Collection<S<A>>
                        ^
Invalid type parameter in getReducedType()
Original type: (τ_0_0.Index) -> τ_0_0.Element
Simplified term: τ_0_0.[Collection:Index]
Longest valid prefix: τ_0_0
Prefix type: τ_0_0

Requirement machine for <τ_0_0 where τ_0_0 : Q>
Rewrite system: {
- [Q].[Q] => [Q] [permanent]
- [Q].A => [Q:A] [permanent]
- [Q].Element => [Q:Element] [permanent]
- [Q].Index => [Q:Index] [permanent]
- [Q].Iterator => [Q:Iterator] [permanent]
- [Q].SubSequence => [Q:SubSequence] [permanent]
- [Q].Indices => [Q:Indices] [permanent]
- [Q].[Q:A] => [Q:A]
- [Q].[Q:Element] => [Q:Element]
- [Q].[Q:Index] => [Q:Index]
- [Q].[Q:Iterator] => [Q:Iterator]
- [Q].[Q:SubSequence] => [Q:SubSequence]
- [Q].[Q:Indices] => [Q:Indices]
- τ_0_0.[Q] => τ_0_0 [explicit]
- τ_0_0.A => τ_0_0.[Q:A]
- τ_0_0.Element => τ_0_0.[Q:Element]
- τ_0_0.Index => τ_0_0.[Q:Index]
- τ_0_0.Iterator => τ_0_0.[Q:Iterator]
- τ_0_0.SubSequence => τ_0_0.[Q:SubSequence]
- τ_0_0.Indices => τ_0_0.[Q:Indices]
}
}
Property map: {
  [Q] => { conforms_to: [Q] }
  τ_0_0 => { conforms_to: [Q] }
}
Conformance paths: {
}
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.      Program arguments: /home/ec2-user/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-09-29-a/usr/bin/swift-frontend -frontend -c -primary-file test10.swift -target x86_64-unknown-linux-gnu -disable-objc-interop -color-diagnostics -new-driver-path /home/ec2-user/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-09-29-a/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /home/ec2-user/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-09-29-a/usr/lib/swift -module-name test10 -o /tmp/TemporaryDirectory.h3zcuH/test10-1.o
1.      Swift version 5.8-dev (LLVM 338153f292479fa, Swift b752d7883c26cea)
2.      Compiling with the current language version
3.      While evaluating request TypeCheckSourceFileRequest(source_file "test10.swift")
4.      While type-checking 'Q' (at test10.swift:4:1)
5.      While type-checking 'subscript(_:)' (at test10.swift:8:5)
```

**Comment by theblixguy** [comment] 2022-10-04 20:56
Reduced:

```swift
struct S<T> {}
protocol P: Collection<S<A>> {
  subscript(index: Int) -> Any { get }
}
```

**Comment by AnthonyLatsis** [comment] 2022-10-05 09:55
Self-contained:

```swift
protocol Collection<Element> {
  associatedtype Element

  subscript(_: Int) -> Element { get }
}

protocol P: Collection<Undefined> {
  subscript(_: Int) -> Any { get }
}
```

**Comment by slavapestov** [comment] 2022-11-01 14:58
Duplicate of https://github.com/apple/swift/issues/61020.

**Closed by slavapestov** 2022-11-01 14:58 UTC
Labels: bug, TypeChecker, compiler crash, Generics
