### ISSUE TITLE
`utils/update-checkout --tag swift-5.9-RELEASE` checks out wrong versions of SwiftPM dependencies

### ISSUE THREAD

**Issue by thekief** [apple/swift#68959] opened 2023-10-04 12:31 UTC
**Description**

I downloaded the current release and tried to rebuild it on M2 macMini. When building without any modifications the build crashes after a few hours.

**Steps to reproduce**

- checkout Swift repository
- `utils/update-checkout --clone --tag  swift-5.9-RELEASE`
- `swift/utils/build-toolchain test_tc`
- wait

**Expected behavior**

The build of the toolchain finishes.

```
...
-- Check for working Swift compiler: /Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc - works
-- Configuring done (0.7s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/tsc
[1/6][ 16%][0.017s] Building C object Sources/TSCclibc/CMakeFiles/TSCclibc.dir/process.c.o
[2/6][ 33%][0.018s] Building C object Sources/TSCclibc/CMakeFiles/TSCclibc.dir/libc.c.o
[3/6][ 50%][0.032s] Linking C static library lib/libTSCclibc.a
[4/6][ 66%][0.382s] Linking Swift static library lib/libTSCLibc.a
[5/6][ 83%][12.484s] Linking Swift shared library lib/libTSCBasic.dylib
[6/6][100%][14.545s] Linking Swift shared library lib/libTSCUtility.dylib
/Users/ob2/swift-compiler/swift-tools-support-core/Sources/TSCUtility/FSWatch.swift:830:13: warning: 'FSEventStreamScheduleWithRunLoop' was deprecated in macOS 13.0: Use FSEventStreamSetDispatchQueue instead.
            FSEventStreamScheduleWithRunLoop(
            ^
/Users/ob2/swift-compiler/swift-tools-support-core/Sources/TSCUtility/FSWatch.swift:837:13: warning: 'FSEventStreamScheduleWithRunLoop' was deprecated in macOS 13.0: Use FSEventStreamSetDispatchQueue instead.
            FSEventStreamScheduleWithRunLoop(self.stream, CFRunLoopGetCurrent(), CFRunLoopMode.defaultMode.rawValue)
            ^
/Users/ob2/swift-compiler/swift-tools-support-core/Sources/TSCUtility/FSWatch.swift:843:13: warning: 'FSEventStreamUnscheduleFromRunLoop' was deprecated in macOS 13.0: Use FSEventStreamSetDispatchQueue instead.
            FSEventStreamUnscheduleFromRunLoop(self.stream, CFRunLoopGetCurrent(), CFRunLoopMode.defaultMode.rawValue)
            ^
/Users/ob2/swift-compiler/swift-tools-support-core/Sources/TSCUtility/IndexStore.swift:395:16: warning: 'init(bytesNoCopy:length:encoding:freeWhenDone:)' was deprecated in macOS 13: String does not support no-copy initialization
        return String(
               ^
env MACOSX_DEPLOYMENT_TARGET=10.15 /opt/homebrew/bin/cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/Users/ob2/swift-compiler/build/buildbot_osx/ninja-build/ninja -DCMAKE_BUILD_TYPE:=Debug -DCMAKE_Swift_FLAGS='-sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -module-cache-path "/Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/tsc/module-cache"' -DCMAKE_Swift_COMPILER:=/Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc -DCMAKE_C_COMPILER:=/Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/clang -DCMAKE_AR:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar -DCMAKE_RANLIB:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -DSwiftSystem_DIR=/Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/swift-system/cmake/modules -DCMAKE_C_FLAGS=-target arm64-apple-macosx10.15 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 /Users/ob2/swift-compiler/swiftpm/../swift-tools-support-core
--- bootstrap: note: Building swift-argument-parser
-- The Swift compiler identification is Apple 5.9
-- Check for working Swift compiler: /Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc
-- Check for working Swift compiler: /Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc - works
-- Could NOT find dispatch (missing: dispatch_DIR)
-- Could NOT find Foundation (missing: Foundation_DIR)
-- Could NOT find XCTest (missing: XCTest_DIR)
-- Configuring done (0.4s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/swift-argument-parser
[1/2][ 50%][0.371s] Linking Swift static library lib/libArgumentParserToolInfo.a
[2/2][100%][10.921s] Linking Swift shared library lib/libArgumentParser.dylib
env MACOSX_DEPLOYMENT_TARGET=10.15 /opt/homebrew/bin/cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/Users/ob2/swift-compiler/build/buildbot_osx/ninja-build/ninja -DCMAKE_BUILD_TYPE:=Debug -DCMAKE_Swift_FLAGS='-sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -module-cache-path "/Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/swift-argument-parser/module-cache"' -DCMAKE_Swift_COMPILER:=/Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc -DCMAKE_C_COMPILER:=/Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/clang -DCMAKE_AR:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar -DCMAKE_RANLIB:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -DBUILD_TESTING=NO -DBUILD_EXAMPLES=NO -DCMAKE_C_FLAGS=-target arm64-apple-macosx10.15 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 /Users/ob2/swift-compiler/swiftpm/../swift-argument-parser
--- bootstrap: note: Building yams
-- The C compiler identification is Clang 13.0.0
-- The Swift compiler identification is Apple 5.9
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Swift compiler: /Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc
-- Check for working Swift compiler: /Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc - works
-- Configuring done (0.6s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/yams
[1/8][ 12%][0.036s] Building C object Sources/CYaml/CMakeFiles/CYaml.dir/src/writer.c.o
[2/8][ 25%][0.041s] Building C object Sources/CYaml/CMakeFiles/CYaml.dir/src/reader.c.o
[3/8][ 37%][0.067s] Building C object Sources/CYaml/CMakeFiles/CYaml.dir/src/parser.c.o
[4/8][ 50%][0.070s] Building C object Sources/CYaml/CMakeFiles/CYaml.dir/src/api.c.o
[5/8][ 62%][0.104s] Building C object Sources/CYaml/CMakeFiles/CYaml.dir/src/emitter.c.o
[6/8][ 75%][0.132s] Building C object Sources/CYaml/CMakeFiles/CYaml.dir/src/scanner.c.o
[7/8][ 87%][0.147s] Linking C static library lib/libCYaml.a
[8/8][100%][9.885s] Linking Swift shared library lib/libYams.dylib
env MACOSX_DEPLOYMENT_TARGET=10.15 /opt/homebrew/bin/cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/Users/ob2/swift-compiler/build/buildbot_osx/ninja-build/ninja -DCMAKE_BUILD_TYPE:=Debug -DCMAKE_Swift_FLAGS='-sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -module-cache-path "/Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/yams/module-cache"' -DCMAKE_Swift_COMPILER:=/Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc -DCMAKE_C_COMPILER:=/Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/clang -DCMAKE_AR:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar -DCMAKE_RANLIB:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -DCMAKE_C_FLAGS=-target arm64-apple-macosx10.15 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 /Users/ob2/swift-compiler/swiftpm/../yams
--- bootstrap: note: Building swift-driver
-- The C compiler identification is Clang 13.0.0
-- The Swift compiler identification is Apple 5.9
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Swift compiler: /Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc
-- Check for working Swift compiler: /Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc - works
-- Configuring done (0.6s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/swift-driver
[1/8][ 12%][0.019s] Building C object Sources/CSwiftScan/CMakeFiles/CSwiftScan.dir/CSwiftScanImpl.c.o
[2/8][ 25%][0.033s] Linking C static library lib/libCSwiftScan.a
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: lib/libCSwiftScan.a the table of contents is empty (no object file members in the library define global symbols)
[3/8][ 37%][12.157s] Linking Swift shared library lib/libSwiftOptions.dylib
[4/8][ 50%][12.603s] Linking Swift executable bin/swift-help
[5/8][ 62%][19.881s] Linking Swift shared library lib/libSwiftDriver.dylib
/Users/ob2/swift-compiler/swift-driver/Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift:310:12: warning: 'init(bytesNoCopy:length:encoding:freeWhenDone:)' was deprecated in macOS 13: String does not support no-copy initialization
    return String(bytesNoCopy: UnsafeMutableRawPointer(mutating: dataPtr),
           ^
/Users/ob2/swift-compiler/swift-driver/Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift:140:33: warning: 'init(_:)' is deprecated: use throwing `init(validating:)` variant instead
        commandLine.appendPath(.init(value))
                                ^
[6/8][ 75%][20.614s] Linking Swift shared library lib/libSwiftDriverExecution.dylib
[7/8][ 87%][20.967s] Linking Swift executable bin/swift-driver
[8/8][100%][21.015s] Linking Swift executable bin/swift-build-sdk-interfaces
env MACOSX_DEPLOYMENT_TARGET=10.15 /opt/homebrew/bin/cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/Users/ob2/swift-compiler/build/buildbot_osx/ninja-build/ninja -DCMAKE_BUILD_TYPE:=Debug -DCMAKE_Swift_FLAGS='-sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -module-cache-path "/Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/swift-driver/module-cache"' -DCMAKE_Swift_COMPILER:=/Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc -DCMAKE_C_COMPILER:=/Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/clang -DCMAKE_AR:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar -DCMAKE_RANLIB:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -DLLBuild_DIR=/Users/ob2/swift-compiler/build/buildbot_osx/llbuild-macosx-arm64/cmake/modules -DSwiftSystem_DIR=/Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/swift-system/cmake/modules -DTSC_DIR=/Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/tsc/cmake/modules -DYams_DIR=/Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/yams/cmake/modules -DArgumentParser_DIR=/Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/swift-argument-parser/cmake/modules -DCMAKE_C_FLAGS=-target arm64-apple-macosx10.15 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 /Users/ob2/swift-compiler/swiftpm/../swift-driver
--- bootstrap: note: Building swift-collections
-- The C compiler identification is Clang 13.0.0
-- The Swift compiler identification is Apple 5.9
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Swift compiler: /Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc
-- Check for working Swift compiler: /Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc - works
-- Configuring done (0.6s)
env MACOSX_DEPLOYMENT_TARGET=10.15 /opt/homebrew/bin/cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/Users/ob2/swift-compiler/build/buildbot_osx/ninja-build/ninja -DCMAKE_BUILD_TYPE:=Debug -DCMAKE_Swift_FLAGS='-sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -module-cache-path "/Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/swift-collections/module-cache"' -DCMAKE_Swift_COMPILER:=/Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc -DCMAKE_C_COMPILER:=/Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/clang -DCMAKE_AR:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar -DCMAKE_RANLIB:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -DCMAKE_C_FLAGS=-target arm64-apple-macosx10.15 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_C_FLAGS=-target arm64-apple-macosx10.15 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 /Users/ob2/swift-compiler/swiftpm/../swift-collections
--- bootstrap: error: Command '['env', 'MACOSX_DEPLOYMENT_TARGET=10.15', '/opt/homebrew/bin/cmake', '-G', 'Ninja', '-DCMAKE_MAKE_PROGRAM=/Users/ob2/swift-compiler/build/buildbot_osx/ninja-build/ninja', '-DCMAKE_BUILD_TYPE:=Debug', '-DCMAKE_Swift_FLAGS=\'-sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -module-cache-path "/Users/ob2/swift-compiler/build/buildbot_osx/swiftpm-macosx-arm64/apple/Products/swift-collections/module-cache"\'', '-DCMAKE_Swift_COMPILER:=/Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/swiftc', '-DCMAKE_C_COMPILER:=/Users/ob2/swift-compiler/build/buildbot_osx/intermediate-install/macosx-arm64/Library/Developer/Toolchains/swift-LOCAL-2023-10-04-a.xctoolchain/usr/bin/clang', '-DCMAKE_AR:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar', '-DCMAKE_RANLIB:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib', '-DCMAKE_C_FLAGS=-target arm64-apple-macosx10.15', '-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15', '-DCMAKE_C_FLAGS=-target arm64-apple-macosx10.15', '-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15', '/Users/ob2/swift-compiler/swiftpm/../swift-collections']' returned non-zero exit status 1.
```

**Environment**
- Swift compiler version info 
```
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
 ``` 
- Xcode version info 
```
Xcode 15.0
Build version 15A240d
```

- Deployment target: 

```
n/a
```

**Comment by MaxDesiatov** [comment] 2023-10-05 12:19
Closing as a duplicate of https://github.com/apple/swift-package-manager/issues/6970. The fact that Apple Silicon is used is not relevant to the issue.

**Closed by MaxDesiatov** 2023-10-05 12:19 UTC
Labels: bug, triage needed
