### ISSUE TITLE
Default arguments aren't checked against the global actor of their function

### ISSUE THREAD

**Issue by KeithBauerANZ** [apple/swift#63118] opened 2023-01-19 22:00 UTC
**Description**

When declaring a function with a global actor requirement, default values of its arguments are checked without that actor requirement.

**Steps to reproduce**

```swift
@MainActor
final class SomeClass {

    static var someConstant: Int { 3 }

    func someMethod(value: Int = SomeClass.someConstant) {}

}
```

`swiftc -strict-concurrency=complete mainactor-default.swift`

**Expected behavior**

The code should compile, since the function must be called on the main actor, it should be OK for the default value of the argument to require the main actor too.

**Actual behavior**

```
mainactor-default.swift:6:44: error: main actor-isolated static property 'someConstant' can not be referenced from a non-isolated context
    func someMethod(value: Int = SomeClass.someConstant) {}
                                           ^
mainactor-default.swift:4:16: note: static property declared here
    static var someConstant: Int { 3 }
               ^
```

**Environment**
- swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
- Xcode 14.2
Build version 14C18

**Comment by johannesd** [comment] 2023-03-31 09:26
I have the same problem!

**Comment by AnthonyLatsis** [comment] 2023-05-02 18:29
Duplicate of #58177

**Closed** 2023-05-02 18:30 UTC
Labels: bug, duplicate, concurrency, compiler, type checker, default arguments, actors, actor isolation, swift 5.9, unexpected error
