### ISSUE TITLE
[SR-14943] Fix-it for changing unsafeBitcast to unsafeDowncast should be more narrow or removed

### ISSUE THREAD

**Issue by typesanitizer** [apple/swift#57285] opened 2021-07-20 01:18 UTC
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14943      |
   |Radar             | rdar://problem/80820402         |
   |Original Reporter | @typesanitizer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, StarterBug        |
   |Assignee          | Rajagopalan (JIRA)      |
   |Priority          | Medium      |

   md5: 3d91228cea2823e2a2396d782c8b9edb

  </details>

**Issue Description:**

According to the documentation, unsafeBitcast expects that the target type is layout-compatible with the type of the value passed in.

OTOH, unsafeDowncast expects that the type of the value *is* the target type (there is a `_debugPrecondition(x is T)`).

Currently, we have a fix-it where we recommend replacing `unsafeBitcast` with `unsafeDowncast`. However, strengthening a precondition like that in a fix-it is generally not OK unless we have some reason to believe that `x is T` will be true.

Here is a code example that can be tested in a playground:

```swift
import Foundation
import UIKit
​
@propertyWrapper
struct UnsafeBitCast<Actual: NSObjectProtocol, Mocked: NSObjectProtocol> {
    init(wrappedValue: Actual?, to mocked: Mocked.Type) {
        self.wrappedValue = wrappedValue
    }
    var wrappedValue: Actual?
    var projectedValue: Mocked? {
        wrappedValue.map({ unsafeBitCast($0, to: Mocked.self) }) // fix-it suggests unsafeDowncast
    }
}
​
class MockUIWindow: NSObject {
    @UnsafeBitCast(to: UIScene.self) var mockWindowScene: MockUIScene? = nil
    init(mockWindowScene: MockUIScene? = .init()) {
        self.mockWindowScene = mockWindowScene
    }
    var windowScene: UIScene? {
        $mockWindowScene
    }
}
​
class MockUIScene: NSObject {
    @objc var activationState: UIScene.ActivationState
    init(activationState: UIScene.ActivationState = .foregroundActive) {
        self.activationState = activationState
    }
}
​
let mockWindow = MockUIWindow()
print(mockWindow.windowScene!.activationState == .foregroundActive)
```

If one applies the fix-it, this code crashes due to the precondition failing. We should either remove the fix-it altogether or only apply it narrowly in the cases where we know for sure that `x is T` will be true.

**Comment by AnthonyLatsis** [comment] 2023-05-11 18:52
Duplicate of #57001

**Closed by AnthonyLatsis** 2023-05-11 18:52 UTC
Labels: bug, duplicate, compiler, good first issue, diagnostics QoI, type checker, generics, casting, swift 5.9, unexpected warning
