### ISSUE TITLE
Type inference is not working properly when creating an instance of the same class from the Generics class

### ISSUE THREAD

**Issue by soranoba** [apple/swift#58413] opened 2022-04-26 04:45 UTC
**Describe the bug**

```swift
public protocol Loader {
    associatedtype ItemType

    func load() -> [ItemType]
}

class ViewController<LoaderType: Loader>: UIViewController where LoaderType.ItemType == Movie
{
    private var loader: LoaderType

    // MARK: - Lifecycle
    init(loader: LoaderType) {
        self.loader = loader
        super.init(nibName: "ViewController", bundle: Bundle(for: type(of: self)))
    }
}
```

The following code in the ViewController's method will result in a compile error, but in other UIViewControllers it will not.

```swift
    @IBAction private func didTapButton(_ sender: UIButton) {
        let vc = ViewController(loader: MovieLoader2())
        present(vc, animated: true, completion: nil)
    }
```

A workaround is to change to the following code:
```swift
    @IBAction private func didTapButton(_ sender: UIButton) {
        let vc = ViewController<MovieLoader2>(loader: MovieLoader2())
        present(vc, animated: true, completion: nil)
    }
```

**To Reproduce**

The reproduction code is here. (You need to specify a branch)
https://github.com/soranoba/iOS-Sandbox/tree/TypeInferenceInGenericsClass

**Expected behavior**

```swift
        // Failed: Cannot convert value of type 'MovieLoader2' to expected argument type 'LoaderType'
        vc = ViewController(loader: MovieLoader2())

```
https://github.com/soranoba/iOS-SandBox/blob/TypeInferenceInGenericsClass/Sample/ViewController.swift#L43-L44

This code fails to compile, but it should compile success.

**Screenshots**
![スクリーンショット 2022-04-26 13 44 08](https://user-images.githubusercontent.com/4954289/165222844-31ddb491-4f7c-40a0-9b34-434cb8d6e774.png)

**Environment (please complete the following information):**
- Xcode 13.3.1
- iOS 15.4
- Swift 5.6

**Additional context**

**Comment by hamishknight** [comment] 2022-04-26 10:04
Unfortunately this is a longstanding behavior, within the context of a generic type such as `ViewController`, a bare reference to `ViewController` is always inferred to be `ViewController<LoaderType>`, even if there is a different contextual type. Changing this would likely be source breaking, and would therefore need to go through Swift Evolution.

Duplicate of https://github.com/apple/swift/issues/44398

**Closed by hamishknight** 2022-04-26 10:04 UTC
Labels: bug
