### ISSUE TITLE
AsyncThrowingStream initializer Failure type is restricted to Swift.Error

### ISSUE THREAD

**Issue by BrentMifsud** [apple/swift#64165] opened 2023-03-07 05:27 UTC
**Description**
The compiler complains if you try to specialize your AsyncThrowingStream with an error type other than Swift.Error.

You get the following error:

`Initializer 'init(unfolding:)' requires the types 'MyClass.Error' and 'any Error' to be equivalent`

OR

`Initializer 'init(_:bufferingPolicy:_:)' requires the types 'MyClass.Error' and 'any Error' to be equivalent`

It seems the cause is that the initializer declarations have the following:

`where Failure == Error`

instead of

`where Failure : Error`

**Steps to reproduce**

```swift
class MyClass {
    enum Error: Swift.Error {
        case somethingWentWrong
    }

    var myStream: AsyncThrowingStream<Void, MyClass.Error> {
        // This initializer will not compile
        return AsyncThrowingStream {
            throw MyClass.Error.somethingWentWrong
        }
    }
}
```

**Expected behavior**
I should be able to specialize my AsyncThrowingStream to have any error type.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/18543934/223327841-646a79fe-54ff-489c-bf4f-4f232df6ce39.png">

**Environment**

- Swift compiler version info 
    - swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51) Target: arm64-apple-macosx13.0
- Xcode version info 
    - Xcode 14.2 Build version 14C18
- Deployment target: 
    - iOS 15+

Happens in both Xcode and playgrounds

There is a workaround:

When initializing a new AsyncThrowingStream, make sure to set the type as follows: `AsyncThrowingStream<MyType, Swift.Error>`

**Comment by ktoso** [comment] 2023-03-08 09:45
cc @phausler tho I suspect this is by design

**Comment by phausler** [comment] 2023-03-08 18:11
this is by design - specific errors end up getting lost during the construction (we have no way to enforce a specific throw is of a given error type). And perhaps nor should the language - specifying the failure type beyond the existential causes explosions of generics matching computation during compilation, making things not only take a long time to compile but it produces horrible failures.

**Comment by ktoso** [comment] 2023-03-08 22:07
Yeah thought so, this may be closed as a won't fix perhaps then?

**Closed** 2023-03-08 22:09 UTC
Labels: bug, will not do, concurrency, triage needed

**Comment by BrentMifsud** [comment] 2023-03-09 18:04
If this is the intended behavior, I am curious why the signature requires us to specify an error type then.

**Comment by ali-ahsan-ali** [comment] 2024-08-13 04:26
@phausler @ktoso With types throws returning in Swift 6. Is it possible for this to be re-opened and revisited?

**Comment by ktoso** [comment] 2024-08-13 09:53
I suggest opening a new issue, reopening issues causes confusing histories. Please make new one about specific operators and their typed throws adoption :)
