### ISSUE TITLE
error: compile command failed due to signal 6

### ISSUE THREAD

**Issue by SusanDoggie** [apple/swift#59773] opened 2022-06-29 06:01 UTC
**Describe the bug**

Failed to build tests with latest swift nightly docker.

`error: compile command failed due to signal 6 (use -v to see invocation)swift-frontend: /home/build-user/swift/lib/SIL/IR/SILInstructions.cpp:82: void buildTypeDependentOperands(SmallVectorImpl<swift::CanOpenedArchetypeType> &, bool, SmallVectorImpl<swift::SILValue> &, swift::SILFunction &): Assertion `def->getFunction() == &F && "def of root opened archetype is in wrong function"' failed.`

logs: https://github.com/SusanDoggie/Doggie/runs/7103807671?check_suite_focus=true
sources: https://github.com/SusanDoggie/Doggie/tree/31806ebe4baaf03f6c1bd4f7432ef027031e3ccd

**Environment (please complete the following information):**
 - latest swift nightly docker

**Comment by slavapestov** [comment] 2022-07-02 02:20
@eeckstein Can you take a look?

**Comment by eeckstein** [comment] 2022-07-06 05:34
ok, it builds fine with a top-of-main compiler and with `-disable-round-trip-debug-types`.
@slavapestov, I'm assigning this to you for the "Failed to reconstruct type" problem.

**Comment by slavapestov** [comment] 2022-07-19 03:20
Reduced:

```swift
import CoreGraphics

public func CGPatternCreate(yStep: CGFloat) {
  typealias A = Int
  let info = UnsafeMutablePointer<A>.allocate(capacity: 1)
}
```

**Comment by slavapestov** [comment] 2022-07-19 03:21
The problem is that CGFloat was moved from CoreGraphics to CoreFoundation with `@_originallyDefinedIn`.

**Closed** 2022-07-19 19:04 UTC
Labels: bug
