### ISSUE TITLE
[SR-14971] Spurious error after wrapped 'var' declaration without type annotation.

### ISSUE THREAD

**Issue by 41412bb9-c79a-4f5a-8a7f-383cb40aa74b** [apple/swift#57313] opened 2021-07-24 00:41 UTC
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14971      |
   |Radar             | None         |
   |Original Reporter | @rintaro      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Parser, StarterBug        |
   |Assignee          | nate041 (JIRA)      |
   |Priority          | Medium      |

   

   md5: b6db08514a985df9a7c359dbc1560fe1

  </details>

**Issue Description:**

``` java
@propertyWrapper
struct Wrap {
  var wrappedValue: Int = 1
}
func test() {
  @Wrap var val
  _ = val
}
```

This results:

``` java
test.swift:8:3: error: found an unexpected second identifier in variable declaration; is there an accidental break?
  _ = val
  ^
test.swift:8:3: note: join the identifiers together
  _ = val
~~^
val_
test.swift:8:7: error: use of local variable 'val' before its declaration
  _ = val
      ^
test.swift:7:13: note: 'val' declared here
  @Wrap var val
            ^
```

But this should be valid syntax.

**Comment by bradleymackey** [comment] 2022-11-30 21:32
Duplicate of #57542

**Closed** 2022-11-30 21:56 UTC
Labels: bug, duplicate, parser, compiler, StarterBug, property wrappers
