### ISSUE TITLE
Set with WritableKeyPath also calls its getter.

### ISSUE THREAD

**Issue by sidepelican** [apple/swift#61401] opened 2022-10-01 06:46 UTC
**Describe the bug**

When set a value with `WritableKeyPath` like `foo[keyPath: \.value] = 42`, The sentence calls `foo.value`'s getter first.

**Steps To Reproduce**

Run the code below.

```swift
struct S {
  var _value: Int = 0
  var value: Int {
    get {
      print("get")
      return _value
    }
    set {
      print("set")
      _value = newValue
    }
  }
}

var s = S()
s[keyPath: \.value] = 42
```

Run with debug mode, `get` appears before `set`.

```
$ swift test.swift
get
set
```

If `-O` is enabled, `get` does not appear.

```
$ swift -O test.swift 
set
```

**Expected behavior**

WritableKeyPath does not call additional getter.

**Environment (please fill out the following information)**
 - OS: macOS 12.5.1 (21G83)
 - Xcode Version/Tag/Branch: Version 14.0 (14A309) Swift 5.7
 
 And Linux Swift 5.7

**Additional context**

In my situation, I had trouble using some propertyWrapper like following. 

```swift
@propertyWrapper
public struct LateInit<Value> {   
    public init() {
        _wrappedValue = nil
    }
    private var _wrappedValue: Value?
    public var wrappedValue: Value {
        get {
            guard let _wrappedValue else {
                fatalError("uninitialized")
            }
            return _wrappedValue
        }
        set {
            _wrappedValue = newValue
        }
    }
}
```

This wrapper is intended  to be called its setter first. 
When using this in some metaprograming and it using a keyPath, may have trouble.

**Comment by theblixguy** [comment] 2022-10-01 13:36
Duplicate of https://github.com/apple/swift/issues/52603

**Closed** 2022-10-01 13:36 UTC
Labels: bug
