### ISSUE TITLE
`@discardableResult` ignored when using `@MainActor`

### ISSUE THREAD

**Issue by NachoSoto** [apple/swift#60548] opened 2022-08-13 15:36 UTC
**Describe the bug**
Starting with Xcode 14 (I believe specifically beta 5), `@discardableResult` is ignored when used together with `@MainActor`.

**Steps To Reproduce**
```swift
enum A {
    @MainActor
    @discardableResult
    func f() -> Int {
        return 1
    }

    func g() async {
        await f()
    }
}
```

**Expected behavior**
Code compiles with no warnings

**Actual behavior**
`await f()` produces a warning:
> Result of call to function returning 'Int' is unused

**Environment (please fill out the following information)**
 - OS: `macOS 13.0`
 - Xcode Version: `14.0 beta 5 (14A5294e)`
 - Swift version: `5.7 (swiftlang-5.7.0.123.8 clang-1400.0.29.50)`

**Additional context**
Removing `@MainActor` (and adding `async` instead so `await` makes sense) from `f` makes the warning go away.

**Comment by xedin** [comment] 2022-08-13 16:24
This is a dupe of https://github.com/apple/swift/issues/60545

**Closed by xedin** 2022-08-13 16:24 UTC
Labels: bug
