### ISSUE TITLE
Unexpected `@_spi` visibility for public function returning C++ type

### ISSUE THREAD

**Issue by GeorgeLyon** [apple/swift#61472] opened 2022-10-06 17:12 UTC
**Describe the bug**
Commit demonstrating bug:  https://github.com/GeorgeLyon/circt/tree/23831ec861f3874cbdc733c30404ce74b892a8a9

I have a C++ CMake target `circt/lib/Bindings/Swift/Bridge` which add functionality not yet bridged by C++ interop (namely, calling `new MLIRContext()`). This target uses the C++ type `MLIRContext`, from a dependent module (`MLIRIR`) with `import_as_ref` and `retain/release:immortal` annotations. I also have a Swift CMake target (`CIRCTSwift`) at `circt/lib/Bindings/Swift/Module` which uses C++ interop to depend on `Bridge`. Finally, I have a test target `test/Bindings/Swift` which imports `CIRCTSwift` as a Swift library and attempts use its API.

In `CIRCTSwift`, there are two public functions: `func fourtyTwo() -> Int` and  `func createMLIRContext() -> mlir.MLIRContext`, the main difference between them being that `mlir.MLIRContext` is a C++ imported with `import_as_ref`. Attempting to compile this project produces the following error when calling `createMLIRContext`, but no similar error is produced when only calling `fourtyTwo`:
```
[build] /workspaces/circt-workspace/circt/test/Bindings/Swift/Bindings.swift:19:15: error: 'createMLIRContext' is inaccessible due to '@_spi' protection level
[build] let context = createMLIRContext()
[build]               ^
[build] /workspaces/circt-workspace/circt/lib/Bindings/Swift/Module/MLIRContext.swift:8:13: note: 'createMLIRContext()' declared here
[build] public func createMLIRContext() -> mlir.MLIRContext {
[build]             ^
```

**Steps To Reproduce**
The easiest way to reproduce this behavior is to 
1) Open up the project in VSCode with Docker running.
2) Execute the VSCode command "Rebuild and reopen this project in a container". 
3) Once the container is opened, execute the "CMake: Configure" command.
4) Build the `circt-swift-bindings-test` target
...

**Expected behavior**
The API is callable

**Screenshots**

**Environment (please fill out the following information)**
This uses Ubuntu 22.04 and the Swift 5.8 snapshot at https://download.swift.org/development/ubuntu2204/swift-DEVELOPMENT-SNAPSHOT-2022-10-03-a/swift-DEVELOPMENT-SNAPSHOT-2022-10-03-a-ubuntu22.04.tar.gz 

CMake settings can befound in `.decontainer/VSCode/settings.json`

**Comment by hyp** [comment] 2022-10-07 17:26
Assigning to @zoecarver as he knows what the issue is and will work on fixing it with @beccadax .

**Comment by zoecarver** [comment] 2022-10-07 17:51
Yep, pretty much!

In more depth: Swift goes to lookup function `swiftFunction() -> Namespace.Record`. It finds the function in the serialized module. It goes to deserialize the return type. It hasn't loaded the clang module yet [1], so it cannot find the return type. It fails to deserialize the function, and reports that it cannot find the function. Swift then looks for the function in other places, which has the side effect of loading the clang modules (and populating the bridging header's lookup table, among other things). It's a swift function, so it can't find it in the clang modules, and still reports that there are no lookup results.

Then, to produce a nice error, Swift does another lookup, this time ignoring the access specifiers. This time the clang modules have been loaded though, so it _does_ find the function in the serialized module! The Swift compiler then says, "this is a public decl, I didn't find anything the first time, but did find something when ignoring access specifiers, so it _must_ be SPI." That's why you get that error.

[1] Normally, what would happen here, is Swift would see that it hasn't loaded the clang module that's be referenced and it would go load that module. However, namespaces are not owned by a module, so they go in the bridging header module (__ObjC). There's nothing to load there (that lookup table gets filled in as a side effect of loading other modules), so we fail to lookup the type.

**Closed** 2023-06-22 16:48 UTC
Labels: bug, c++ interop

**Comment by furby-tm** [comment] 2023-11-20 08:24
Sorry to add noise on a potentially fixed issue; however, I was able to reproduce this issue when attempting to "hop" a c++ namespace from a swift typealias.

Example:
```swift
// ModuleA/ModuleA.swift

// a module defining this typealias
public typealias SomeType = cxxnamespace.SomeCxxType
```
```swift
// ModuleB/ModuleB.swift
import ModuleA

// would cause SomeType to produce error: 'SomeType' is inaccessible due to '@_spi' protection level
SomeType.doSomething()
```

Swift version:
```
swift-driver version: 1.87.2 Apple Swift version 5.9 (swiftlang-5.9.2.1.6 clang-1500.1.0.1.1)
Target: arm64-apple-macosx14.0
```

**Comment by masters3d** [comment] 2023-12-19 17:09
@egorzhdan  @zoecarver could we reopen this for type alias issues stated above? Or would you prefer a new issue filed?

**Comment by furby-tm** [comment] 2024-01-15 09:43
I can confirm this bug is still prevalent when using type aliases in the latest _release_ though I have not yet tried this with a _prerelease_ version of swift. To reproduce this issue specifically, you should be able to do so when creating swift type aliases to C++ namespaces, thank you!
