### ISSUE TITLE
Unable to use `MainActor.assumeIsolated`, results in "JIT session error: Symbols not found"

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift#74181] opened 2024-06-06 15:32 UTC
### Description

Reduced test case attached. This works in Swift 5.10. In Swift 6 mode, this crashes.

### Reproduction

```swift
func mainActorAssume() {
	MainActor.assumeIsolated {
	}
}
```

### Stack dump

```text
JIT session error: Symbols not found: [ _$sScM14assumeIsolated_4file4linexxyYbKScMYcXE_s12StaticStringVSutKs8SendableRzlFZ ]
Failed to materialize symbols: { (main, { _main, _$s4test15mainActorAssumeyyF }) }
```

### Expected behavior

Compiles cleanly with Swift 5

### Environment

Apple Swift version 6.0-dev (LLVM 0872cb59adca699, Swift 36e0c9e4c07945a)
Target: arm64-apple-macosx14.0

**Comment by mattmassicotte** [comment] 2024-06-06 15:33
Looks very similar to https://github.com/apple/swift/issues/74104

**Comment by hborla** [comment] 2024-06-06 22:17
Nice, I think you just found an ABI break caused by global actor isolation on a function type implying `@Sendable`, which is gated behind the `GlobalActorIsolatedTypesUsability` upcoming feature / Swift 6 mode. Seems like the caller thinks the mangling is different due to that inference.

**Comment by Jnosh** [comment] 2024-06-06 22:26
Potentially related to #74009 as well?

**Comment by hborla** [comment] 2024-06-07 05:53
@Jnosh yes, this is the same as your issue!

**Comment by hborla** [comment] 2024-06-07 05:54
Duplicate of https://github.com/apple/swift/issues/74009

**Closed** 2024-06-07 05:55 UTC
Labels: bug, crash, triage needed
