### ISSUE TITLE
Possible bug when property wrapper's wrappedValue marked as global actor

### ISSUE THREAD

**Issue by hiragram** [apple/swift#63346] opened 2023-02-01 10:00 UTC
**Description**

Property wrapper seems to have a problem if its `wrappedValue` is marked with global actor.

When a property wrapper's `wrappedValue` is `@MainActor` , a struct whole itself which has a property using the property wrapper becomes `@MainActor`. This behavior looks incorrect.

Minimal reproduction code below.

**Steps to reproduce**

```swift
@propertyWrapper struct Wrap<T> {
    init(wrappedValue: T) {
        self.wrappedValue = wrappedValue
    }

    @MainActor var wrappedValue: T
}

struct Foo {
    @Wrap var a: Int = 1
}

Foo() // Error
```

The error is: 
```
error: call to main actor-isolated initializer 'init()' in a synchronous nonisolated context
note: calls to initializer 'init()' from outside of its actor context are implicitly asynchronous
```

**Other cases**

- `var b: Wrap<Int> = .init(wrappedValue: 1)` instead of `@Wrap var a: Int = 1`
  - Compilation succeeds
- remove `@MainActor` from `wrappedValue`
  - Compilation succeeds

**How I met this problem**

I met this problem when using SwiftUI. Reproduction code:

```swift
class ViewModel: ObservableObject {
    var value: Int = 1
}

struct Foo: View, Equatable {
    @ObservedObject var vm: ViewModel

    nonisolated static func == (lhs: Foo, rhs: Foo) -> Bool {
        lhs.vm.value == rhs.vm.value // Main actor-isolated property 'vm' can not be referenced from a non-isolated context
    }

    var body: some View {
        EmptyView()
    }
}
```

**Expected behavior**

Actor of `wrappedValue` does not affect to actor of type which owns the property wrapper as a property.

**Environment**
- Swift compiler version info 5.7.3, 5.9-dev
- https://swiftfiddle.com/?c=H4sIAAAAAAAAA21QwQqCQBD9lWFPCqV4XUrsInToJnURYjOrBduVdTRE%2FPfGXQWJ5jRv3ps3jxlYwThLaqPr0mB%2FMaKmBho0bYEwwV0Ww5AroJJKovexkvtZVG3JIfMXcqqmrB7BWgB7WEOnHHPlmuQkpDoUqA10wsCPc66scI6Sar1cSqZYdkNwOCqkI5FjwtCOb9wlJy4mMviTO%2FJn%2BysJyNsjzDaso2co%2BXxh1W%2FfFI6NX881%2Bk8hAQAA

Thanks @omochi for supporting investigation.

**Comment by hborla** [comment] 2023-10-26 17:54
This is addressed by [SE-0401: Remove Actor Inference caused by Property Wrappers](https://github.com/apple/swift-evolution/blob/main/proposals/0401-remove-property-wrapper-isolation.md)

**Closed by hborla** 2023-10-26 17:54 UTC
Labels: bug, concurrency, compiler, type checker, property wrappers, actor, swift 5.7, actor isolation
