### ISSUE TITLE
Error messages for failure to infer generic parameter and opaque result type should be aligned

### ISSUE THREAD

**Issue by AnthonyLatsis** [apple/swift#63291] opened 2023-01-28 21:24 UTC
**Description**

Consider these two errors:
```swift
func f1<T>() -> T { fatalError() }
f1() // error: generic parameter 'T' could not be inferred

func f2() -> Optional<some Sequence> { 
  return nil // error: cannot infer underlying type for opaque result 'Optional<some P>' from return expression
}
```

Interestingly, the *second error* is a tailored version of the first, because the underlying type of an opaque result type is in fact a generic parameter of the implicit opaque result type declaration. So these errors are fundamentally one and the same, but the difference in their phrasings is hardly enlightening in this respect. A wording for the *second error* that is more similar to that of the much more familiar *first error* would facilitate [our efforts in presenting this feature as an extension of the generics system](https://docs.swift.org/swift-book/LanguageGuide/OpaqueTypes.html#ID614). For example, `underlying type for opaque result type '...' could not be inferred from return expression`.

**Comment by Kaushik-Iyer** [comment] 2023-02-03 11:53
Is this issue still open?

**Comment by AnthonyLatsis** [comment] 2023-02-03 18:49
It sure is!

**Comment by Rajveer100** [comment] 2023-02-04 11:11
Hi there, Rajveer (aka Rajveer100) here, I am completely new to contributing to swift, and want to devote my time in doing so from now, I have followed the steps from the guide in the readme file provided regarding cloning, getting started...Needed little push for initial start to get the flow. 

Thanks.

**Comment by AnthonyLatsis** [comment] 2023-02-04 14:25
Let us know if you want to work on this and need any guidance!

**Comment by Rajveer100** [comment] 2023-02-04 14:30
Yes...I need guidance, and would love to contribute...Please assist me.

**Comment by AnthonyLatsis** [comment] 2023-02-04 16:16
Is there anything specific you need help with?

**Comment by Rajveer100** [comment] 2023-02-04 16:19
Well, as I said, I am totally new to contributing to this repo, so I am clueless on how to fix an issue, so was looking for starter good first issue tags, and one of them is this one.

**Comment by Rajveer100** [comment] 2023-02-04 16:25
This is my CV and some info about me, just for assuring my coding knowledge and credibility:-

[](https://www.linkedin.com/in/rajveer-singh-bharadwaj-5504b31a4)

[](https://github.com/Rajveer100/Personal-CV/blob/main/Resume-Latest.pdf)

**Comment by AnthonyLatsis** [comment] 2023-02-04 21:32
If it’s the compiler, the only one thing that I would call a requirement in terms of skills is experience with Swift, and at least a bit with C++.
___

Were you successful in building the project per the guide? If so, start with writing a test that reproduces the issue.

**Comment by Rajveer100** [comment] 2023-02-05 05:41
Sounds Great! So regarding the requirements part, C++ is a daily on the go with high proficiency due to competitive programming, while also having intermediate knowledge in Swift due to iOS Development. Just for my info, skills and credibility of what I know, here are some links (yeah it might not sound much relatable for the current conversation, but maybe you could go through it) : -

[https://github.com/Rajveer100/Personal-CV/blob/main/Resume-Latest.pdf](url) 
[https://www.linkedin.com/in/rajveer-singh-bharadwaj-5504b31a4](url)

Coming back to the "Getting Started" part:

- I have cloned the project successfully via SSH using the commands mentioned.
- Installed dependencies (cmake, ninja, sccache)
- Have done the actual build command which creates this file -> **swift-project/build/Ninja-RelWithDebInfoAssert** (with this error message :-

  **CMake Error at cmake/modules/SwiftSharedCMakeConfig.cmake:16 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  cmake/modules/SwiftSharedCMakeConfig.cmake:253 (swift_common_standalone_build_config_llvm)
  CMakeLists.txt:715 (swift_common_standalone_build_config)**

So what would be the next step after this...

**Comment by AnthonyLatsis** [comment] 2023-02-05 23:35
* Is this your first time cloning & building the project?
* Have you [spot checked your dependencies](https://github.com/apple/swift/blob/main/docs/HowToGuides/GettingStarted.md#spot-check-dependencies)?
* Before I ask for more details, see if the guide’s troubleshooting list helps you out.

**Comment by Rajveer100** [comment] 2023-02-06 08:52
Ok, good news, I just deleted everything, and re-performed all operations from the beginning, and got a successful build report:

--- Build Script Analyzer ---
Build Script Log: /Users/rajveersingh/swift-project/build/.build_script_log
Build Percentage 	 Build Duration (sec) 	 Build Phase
================ 	 ==================== 	 ===========
54.0%             	 1083.77               	 Building llvm
41.7%             	 837.12                	 macosx-arm64-swift-build
2.2%              	 43.75                 	 Building earlyswiftdriver
2.0%              	 40.1                  	 Building earlyswiftsyntax
0.1%              	 2.31                  	 Building cmark
0.0%              	 0.07                  	 macosx-arm64-swift-test
0.0%              	 0.06                  	 macosx-arm64-swift-install
0.0%              	 0.04                  	 merged-hosts-lipo-core
0.0%              	 0.04                  	 macosx-arm64-extractsymbols
0.0%              	 0.04                  	 macosx-arm64-package
0.0%              	 0.04                  	 merged-hosts-lipo
Total Duration: 2007.34 seconds (33m 27s)

**Comment by Rajveer100** [comment] 2023-02-06 08:56
Above build was generated after this command:

**utils/build-script --skip-build-benchmarks \
  --skip-ios --skip-watchos --skip-tvos --swift-darwin-supported-archs "$(uname -m)" \
  --sccache --release-debuginfo --swift-disable-dead-stripping**

**Comment by Rajveer100** [comment] 2023-02-06 08:57
Should I execute the below command now (asking you just so that I don't encounter any problems) ?

**utils/build-script --swift-darwin-supported-archs "$(uname -m)" --xcode --clean**

**Comment by Rajveer100** [comment] 2023-02-06 08:58
Please guide me from this part:

[Using Ninja with Xcode](https://github.com/apple/swift/blob/main/docs/HowToGuides/GettingStarted.md#using-ninja-with-xcode)

**Comment by AnthonyLatsis** [comment] 2023-02-06 10:24
I can only guide you if you have questions or are stuck!

**Comment by Rajveer100** [comment] 2023-02-06 10:28
Alright, I will try to finish the remaining procedure as mentioned above, just to confirm, I have to first do this right (after my Ninja setup is complete) ? 

"Were you successful in building the project per the guide? If so, start with reproducing the issue: paste the reproducer into an empty Swift file and feed it to the locally built compiler. You can find tips on how to run a locally built compiler in the GettingStarted guide."

**Comment by Rajveer100** [comment] 2023-02-06 10:36
Ok so what must I do for this part:

**"Add the generated Xcode projects or Swift packages that are relevant to your tasks to your workspace. All the Xcode projects can be found among the build artifacts under build/Xcode-ReleaseAssert"**

**Comment by Rajveer100** [comment] 2023-02-06 10:37
I am currently setting up using Xcode Workspace..

**Comment by AnthonyLatsis** [comment] 2023-02-06 10:38
> Ok so what must I do for this part.

This issue involves editing compiler diagnostics, so you need to add the compiler sources to your workspace. See the examples.

**Comment by Rajveer100** [comment] 2023-02-06 10:40
Before continuing, I hope you don't mind my frequent doubts...

**Comment by AnthonyLatsis** [comment] 2023-02-06 10:43
I don’t mind them at all. As long as you read the documentation/guide first, your questions will help us improve those resources for future newcomers.

**Comment by Rajveer100** [comment] 2023-02-06 10:46
Thank you so much, I really appreciate it, I am so excited and enjoying it!

Alright, coming back, so what would be the best place to create the workspace, as the path really matter right...(And also the appropriate name for it).

**Comment by AnthonyLatsis** [comment] 2023-02-06 10:54
I only ever had a single checkout, so I created the workspace in the `/build` directory. It’s up to you though, the configuration is invariant in that respect.

**Comment by Rajveer100** [comment] 2023-02-06 10:54
Also, I wanted to change the directory path of **swift-project** to another location on my computer, is it ok to do so, or would it cause issues?

**Comment by AnthonyLatsis** [comment] 2023-02-06 10:57
> Also, I wanted to change the directory path of swift-project to another location on my computer, is it ok to do so, or would it cause issues?

AFAIK the only thing that matters is that all checkout dependencies are is the same directory as `swift/`.

**Comment by Rajveer100** [comment] 2023-02-06 11:03
Unable to find the mentioned file to add in the workspace I created:

If you are aiming for the compiler, add **build/Xcode-ReleaseAssert/swift-macosx-*/Swift.xcodeproj**

**Comment by Rajveer100** [comment] 2023-02-06 11:06
Ok I found it, it's actually named as **/build/Xcode-MinSizeRelAssert/swift-macosx-arm64**

**Comment by AnthonyLatsis** [comment] 2023-02-06 11:07
> Is it this one?

Yep, see? That’s a typo right there.

**Comment by Rajveer100** [comment] 2023-02-06 11:08
Actually I think that isn't a typo, as the documentation says that it's mentioned for Intel-based Macs, I have a Mac with M1 Pro chip...

**Comment by Rajveer100** [comment] 2023-02-06 11:10
Oh, alright!

**Comment by Rajveer100** [comment] 2023-02-06 11:11
So I just straight up add this **/build/Xcode-MinSizeRelAssert/swift-macosx-arm64** file to my workspace?

**Comment by AnthonyLatsis** [comment] 2023-02-06 11:12
Just the Xcode project, not the entire directory.

**Comment by Rajveer100** [comment] 2023-02-06 11:12
I mean the **Swift.xcodeproj** specifically in this folder.

**Comment by Rajveer100** [comment] 2023-02-06 11:13
Yep ok.

**Comment by Rajveer100** [comment] 2023-02-06 11:14
This file isn't needed right **swift/SwiftCompilerSources/Package.swift**?

**Comment by AnthonyLatsis** [comment] 2023-02-06 11:18
No, these diagnostics belong to the C++ part.

**Comment by AnthonyLatsis** [comment] 2023-02-06 11:19
> as the documentation says that it's mentioned for Intel-based Macs

Where is this mentioned?

**Comment by Rajveer100** [comment] 2023-02-06 11:20
In the following sections, for simplicity, we will assume that you are using a Ninja-RelWithDebInfoAssert build on macOS running on an Intel-based Mac, unless explicitly mentioned otherwise. You will need to slightly tweak the paths for other build configurations.

Right above troubleshooting build issues...

**Comment by AnthonyLatsis** [comment] 2023-02-06 11:29
If you want to build in Xcode as opposed to the command line, you will have to manually create and configure Xcode targets and hook them up to `ninja` commands. `swift-frontend` is the only target you need. The next step explains how to configure the Xcode target.

**Comment by AnthonyLatsis** [comment] 2023-02-06 11:31
> Right above troubleshooting build issues

I see, thanks. The part about the architecture is no longer relevant.

**Comment by Rajveer100** [comment] 2023-02-06 11:55
In the arguments option for setting up the Xcode Environment, is it supposed to be like this:

**

> $(ACTION) swift-frontend

**

**Comment by AnthonyLatsis** [comment] 2023-02-06 12:01
Which step is this exactly?

**Comment by Rajveer100** [comment] 2023-02-06 12:04
In the Info pane of the target settings, set

- Build Tool to the absolute path of the ninja executable (the output of which ninja on the command line)
- Arguments to the Ninja target name (e.g. swift-frontend)
- Directory to the absolute path of the directory where the Ninja target lives. For Swift targets (the compiler, standard library, runtime, and related tooling), this is the build/Ninja-*/swift-macosx-* directory.

The 2nd one.

**Comment by AnthonyLatsis** [comment] 2023-02-06 12:15
The target name is `swift-frontend`, so just that. Did Xcode add a `$(ACTION)` placeholder or something to the field?

**Comment by Rajveer100** [comment] 2023-02-06 12:18
Yeah actually Xcode initially has **$(ACTION)**, so I don't know whether I should replace **"ACTION"** with **swift-frontend**, or should I do the way I asked above...

**Comment by AnthonyLatsis** [comment] 2023-02-06 12:20
I suggest we try without it and hope the docs won’t need to branch over different Xcode version.

**Comment by Rajveer100** [comment] 2023-02-06 12:34
So you mean I should leave it as it is?

**Comment by AnthonyLatsis** [comment] 2023-02-06 12:36
I mean without the `$(ACTION)`.

**Comment by Rajveer100** [comment] 2023-02-06 12:47
So that actually completes Ninja Xcode Setup part...next part is **Editing**...
Before that I need to do this right 
[Locally built compiler to build X](locally built compiler to build X)?

**Comment by Rajveer100** [comment] 2023-02-06 12:48
So that actually completes Ninja Xcode Setup part...next part is **Editing**...
Before that I need to do this right?

[Locally built compiler to build X](https://github.com/apple/swift/blob/main/docs/HowToGuides/FAQ.md#using-a-locally-built-toolchain)

**Comment by Rajveer100** [comment] 2023-02-06 13:18
I created a new file, and pasted the issue source code, ran the code in the xcworkspace locally I just created using Ninja Xcode Setup, and am successfully getting the error which you mentioned...

So that completes till where you said to do, i.e, the locally built compilation to generate the same issue.

What's the next step...

**Comment by Rajveer100** [comment] 2023-02-06 13:19
```
/Users/rajveersingh/swift-project/build/Compiler-Diagnostics/GenericParameterError.swift:9:1: error: generic parameter 'T' could not be inferred
f1() // error: generic parameter 'T' could not be inferred
^
/Users/rajveersingh/swift-project/build/Compiler-Diagnostics/GenericParameterError.swift:8:6: note: in call to function 'f1()'
func f1<T>() -> T { fatalError() }
     ^
/Users/rajveersingh/swift-project/build/Compiler-Diagnostics/GenericParameterError.swift:12:10: error: cannot infer underlying type for opaque result 'Optional<some Sequence>' from return expression
  return nil // error: cannot infer underlying type for opaque result 'Optional<some P>' from return expression
         ^
Program ended with exit code: 1
```

**Comment by AnthonyLatsis** [comment] 2023-02-06 13:36
> [Locally built compiler to build X](https://github.com/apple/swift/blob/main/docs/HowToGuides/FAQ.md#using-a-locally-built-toolchain)

Well, you can, but those instruction are meant for smuggling a locally built Swift compiler into an existing toolchain to build Swift packages and Xcode projects. For the purposes of this issue, specifying arguments that are passed to the executable in the Xcode scheme is enough. If you look carefully, the GettingStarted guide shows how to build the compiler on the command line too.

**Comment by AnthonyLatsis** [comment] 2023-02-06 13:51
Keep reading the guide, you might find some valuable resources at the end. [Searching for keywords](https://github.com/apple/swift/blob/main/docs/HowToGuides/FAQ.md#where-can-i-find-documentation-on-x) apart from reading is often very helpful too.

**Comment by Rajveer100** [comment] 2023-02-06 18:30
Which file in Swift would deal with generics, so that I can figure out to fix this issue, i.e., merge the two errors ?

**Comment by tbkka** [comment] 2023-02-06 18:35
To track down where the error is being generated, use `git grep` (or something similar) to search the code for the error message.  That will show you where the message is defined.  You can then search for the error message identifier to see where the error is actually being detected.

**Comment by AnthonyLatsis** [comment] 2023-02-06 18:42
The other approach is to use a [frontend flag](https://github.com/apple/swift/blob/main/docs/DebuggingTheCompiler.md#finding-diagnostic-names).

**Comment by Rajveer100** [comment] 2023-02-06 18:42
Hey, nice to meet you too! So I guess I got my first two mentors namely, Anthony and Tim...
@AnthonyLatsis @tbkka 

So you mean I should track down the source of error production site using grep commands first, if I haven't misunderstood?

**Comment by AnthonyLatsis** [comment] 2023-02-06 18:53
Yes, the goal is to find where the error message is defined, so you can edit it. You can either try `grep`ing it or use the flag.

**Comment by Rajveer100** [comment] 2023-02-07 08:02
Does this file **/swift-project/swift/test/Generics** deal with the generated error, cause when I used the git grep command, I seemed to find all such errors are generated in this **/test** folder?

**Comment by Rajveer100** [comment] 2023-02-07 08:07
I think I am definitely doing some mistake...please correct me.

**Comment by Rajveer100** [comment] 2023-02-07 08:22
For example, for the opaque result, I found this:

> `git grep --ignore-case "cannot infer underlying type for opaque result"                   
include/swift/AST/DiagnosticsSema.def:      "cannot infer underlying type for opaque result %0 from return expression",
test/type/opaque.swift:  return nil // expected-error{{cannot infer underlying type for opaque result 'Optional<some Collection<Int>>' from return expression}}
test/type/opaque.swift:    return nil // expected-error{{cannot infer underlying type for opaque result 'Optional<some Collection<Int>>' from return expression}}
test/type/opaque.swift:  return nil // expected-error{{cannot infer underlying type for opaque result 'Optional<some Collection<Int>>' from return expression}}
test/type/opaque_return_named.swift:func f1() -> <T, U, V> T { () } // expected-error{{cannot infer underlying type for opaque result 'T' from return expression}}
test/type/opaque_return_named.swift:  // expected-error@-2{{cannot infer underlying type for opaque result 'T' from return expression}}`

**Comment by AnthonyLatsis** [comment] 2023-02-07 10:49
The `test` directory, as its name suggests, is part of the test suite, not the compiler sources. You see occurrences of the error message among test files because there are test cases that verify the emission of that error. Try to find an occurrence that looks like a definition of string template. `grep` is good and all, but have you tried searching in the workspace, as you would do in a regular application project?

**Comment by Rajveer100** [comment] 2023-02-07 11:07
Actually the result is also found in **include/swift/AST/DiagnosticsSema.def** :

`ERROR(cannot_infer_underlying_for_opaque_result,none,
      "cannot infer underlying type for opaque result %0 from return expression",
      (Type))`

**Comment by Rajveer100** [comment] 2023-02-07 11:09
Looking around for more such results...

**Comment by Rajveer100** [comment] 2023-02-07 11:18
Also, I surprisingly seem to notice several warnings related to **.size()** function, which in C++ returns a **size_t** type, which causes overflow...

**Comment by Rajveer100** [comment] 2023-02-07 12:04
Something like this?

```
void MissingGenericArgumentsFailure::emitGenericSignatureNote(
    ASTNode anchor) const {
  auto &solution = getSolution();
  auto *paramDC = getDeclContext();

  if (!paramDC)
    return;

  auto *GTD = dyn_cast<GenericTypeDecl>(paramDC);
  if (!GTD || anchor.is<Expr *>())
    return;

  auto getParamDecl =
      [](const ConstraintLocator *locator) -> GenericTypeParamDecl * {
    return locator->isForGenericParameter()
               ? locator->getGenericParameter()->getDecl()
               : nullptr;
  };

  llvm::SmallDenseMap<GenericTypeParamDecl *, Type> params;
  for (auto &entry : solution.typeBindings) {
    auto *typeVar = entry.first;

    auto *GP = typeVar->getImpl().getGenericParameter();
    if (!GP)
      continue;

    auto type = resolveType(typeVar);
    assert(!type->is<TypeVariableType>());

    // If this is one of the defaulted parameter types, attempt
    // to emit placeholder for it instead of `Any`.
    if (llvm::any_of(solution.DefaultedConstraints,
                     [&](const ConstraintLocator *locator) {
                       return GP->getDecl() == getParamDecl(locator);
                     }))
      continue;

    params[GP->getDecl()] = type;
  }

  auto getPreferredType = [&](const GenericTypeParamDecl *GP) -> Type {
    auto type = params.find(GP);
    return (type == params.end()) ? Type() : type->second;
  };

  auto baseType = anchor.dyn_cast<TypeRepr *>();
  if (!baseType)
    return;

  SmallString<64> paramsAsString;
  if (TypeChecker::getDefaultGenericArgumentsString(paramsAsString, GTD,
                                                    getPreferredType)) {
    auto diagnostic = emitDiagnosticAt(
        baseType->getLoc(), diag::unbound_generic_parameter_explicit_fix);

    if (auto *genericTy = dyn_cast<GenericIdentTypeRepr>(baseType)) {
      // If some of the eneric arguments have been specified, we need to
      // replace existing signature with a new one.
      diagnostic.fixItReplace(genericTy->getAngleBrackets(), paramsAsString);
    } else {
      // Otherwise we can simply insert new generic signature.
      diagnostic.fixItInsertAfter(baseType->getEndLoc(), paramsAsString);
    }
  }
}
```

In the **CSDiagnostics** file, the **unbound_generic_parameter** call via **diag::** seems to be the one...

**Comment by AnthonyLatsis** [comment] 2023-02-07 12:16
This is where an error message with id `unbound_generic_parameter` gets emitted, but where is the message template itself defined?

**Comment by AnthonyLatsis** [comment] 2023-02-07 12:46
You may not realize, but you already found it — the macro — earlier.

**Comment by Rajveer100** [comment] 2023-02-07 12:47
Wait, could you point out, I too actually thought so...

**Comment by AnthonyLatsis** [comment] 2023-02-07 12:55
Search for the diagnostic id (`unbound_generic_parameter`). There should be only one occurrence where the id is a macro argument, in a huge file where all the diagnostic messages used in semantic analysis are defined.

**Comment by Rajveer100** [comment] 2023-02-07 12:56
```
include/swift/Migrator/FixitFilter.h=struct FixitFilter {
include/swift/Migrator/FixitFilter.h:        Info.ID == diag::unbound_generic_parameter_explicit_fix.ID ||
```

**Comment by AnthonyLatsis** [comment] 2023-02-07 13:17
This is a different id, but regardless, the id isn’t a macro argument here, is it? This is an expression.

**Comment by AnthonyLatsis** [comment] 2023-02-07 13:25
If you’re having trouble understanding what I’m getting at, forget about the macro and try to find the error message (not in `test`, since we already know that those are tests, not compiler sources). Nothing fancy, it’s just a string constant containing format specifiers like `%0`.

**Comment by Rajveer100** [comment] 2023-02-07 13:34
> Actually the result is also found in **include/swift/AST/DiagnosticsSema.def** :
> 
> `ERROR(cannot_infer_underlying_for_opaque_result,none, "cannot infer underlying type for opaque result %0 from return expression", (Type))`

This?

**Comment by AnthonyLatsis** [comment] 2023-02-07 13:36
Yes!

**Comment by Rajveer100** [comment] 2023-02-07 13:36
I actually already mentioned this earlier...

**Comment by AnthonyLatsis** [comment] 2023-02-07 13:41
What made you doubt that this is where the message is defined?

**Comment by Rajveer100** [comment] 2023-02-07 13:43
You mean to ask what was my approach to find the issue in a certain place?

**Comment by AnthonyLatsis** [comment] 2023-02-07 13:48
You used `grep` to search for a substring of the error message in the repo, to find a place the error message is defined, and the search produced multiple results. What I mean is, what made you doubt that `include/swift/AST/DiagnosticsSema.def` is the right place?

**Comment by Rajveer100** [comment] 2023-02-07 13:55
Well, I will tell you how I proceeded with this from the beginning...

So, firstly I used **git grep** command inside the **/swift-project/swift** directory, and then I found the initial **/test** file as you know...

But since that wasn't helpful, I used the **Control + Command + F** command in the workspace I am using, with certain different keywords of the error itself, like, "generic expression", "opaque result", "from return expression", and went through bunch of matching files...

Later saw this Diagnostic file, which I reporter earlier itself, as it seemed like a template to me, due to the formatting, and in various places it was called by using **diag::** with error to be called...

**Comment by AnthonyLatsis** [comment] 2023-02-07 16:28
Okay, now that we’ve found the message, I trust you can figure out how to modify it and test your changes. Once you’re happy with the new message, don’t forget to update any tests that verify the old message!

**Comment by Rajveer100** [comment] 2023-02-07 18:44
So I changed the second error type to align together, I have done the Ninja Re Build for the compiler using this:

`ninja -C ../build/Ninja-RelWithDebInfoAssert/swift-macosx-$(uname -m) bin/swift-frontend`

Is the Incremental Build command needed?

And what do you mean by "don’t forget to update any tests that verify the old message!", you meant running tests command?

**Comment by AnthonyLatsis** [comment] 2023-02-07 19:44
> I have done the Ninja Re Build for the compiler using this

Were you not using Xcode to build and run?

**Comment by Rajveer100** [comment] 2023-02-08 04:53
Yes, I am using Xcode...Just wanted to run the command, so what would be the next step?

**Comment by Rajveer100** [comment] 2023-02-08 10:35
The command was necessary...Because, the changes I made to the code, weren't reflected until I did the rebuild using the command I mentioned...

**Comment by AnthonyLatsis** [comment] 2023-02-08 11:05
Oh, you were not able to reproduce the changes when building with Xcode, right? Please try passing `bin/swift-frontend` rather than just `swift-frontend` in the target settings, that should fix things.

**Comment by Rajveer100** [comment] 2023-02-08 11:09
But my run executable is already set to `bin/swift-frontned`

**Comment by Rajveer100** [comment] 2023-02-08 11:10
I will double check...one sec

**Comment by Rajveer100** [comment] 2023-02-08 11:12
I hope you meant the run executable, that's already set as per the guide, i.e., build/swift-frontend...

**Comment by Rajveer100** [comment] 2023-02-08 11:17
Oh wait, I changed the `ARGUMENTS` in the info to `build/swift-frontend`, now it's working without the Ninja command

**Comment by Rajveer100** [comment] 2023-02-08 11:18
So what would be the next step...

**Comment by AnthonyLatsis** [comment] 2023-02-08 11:39
The next step is to update the tests. `grep` for any occurrences of the old error message in the `test` directory to find places that need amendments.

**Comment by Rajveer100** [comment] 2023-02-08 11:48
```
test/type/opaque.swift:  return nil // expected-error{{cannot infer underlying type for opaque result 'Optional<some Collection<Int>>' from return expression}}
test/type/opaque.swift:    return nil // expected-error{{cannot infer underlying type for opaque result 'Optional<some Collection<Int>>' from return expression}}
test/type/opaque.swift:  return nil // expected-error{{cannot infer underlying type for opaque result 'Optional<some Collection<Int>>' from return expression}}
test/type/opaque_return_named.swift:func f1() -> <T, U, V> T { () } // expected-error{{cannot infer underlying type for opaque result 'T' from return expression}}
test/type/opaque_return_named.swift:  // expected-error@-2{{cannot infer underlying type for opaque result 'T' from return expression}}
```

These are the ones I found...

**Comment by Rajveer100** [comment] 2023-02-08 17:23
If I am not wrong, the comments need to be edited right?

**Comment by Rajveer100** [comment] 2023-02-08 17:26
Alright I have done it, what's the next step...

**Comment by Rajveer100** [comment] 2023-02-09 05:14
I ran the tests, and it passed successfully for both the files `test/type/opaque.swift` and `test/type/opaque_return_named.swift`

**Comment by Rajveer100** [comment] 2023-02-09 05:48
I have committed the changes, please look into it @AnthonyLatsis

**Comment by Rajveer100** [comment] 2023-02-09 09:42
Sure.

**Comment by AnthonyLatsis** [comment] 2023-02-09 09:43
You may also want to read through our [commit message formatting recommendations](https://www.swift.org/contributing/#commit-messages).

**Closed** 2023-02-13 07:19 UTC
Labels: improvement, compiler, good first issue, diagnostics QoI, type checker, generics, opaque types
