### ISSUE TITLE
CommandLine.arguments can contain incorrect contents on Linux

### ISSUE THREAD

**Issue by gwynne** [apple/swift#69658] opened 2023-11-05 00:54 UTC
**Description**
In Docker Desktop for Mac 4.25.0, a change was made to the Rosetta 2-based Intel emulation feature which slightly changes the format of `/proc/<pid>/cmdline` in `x86_64` Docker containers. This change completely breaks Swift's toolchain and most Swift-based executables due to the reliance of `CommandLine.arguments` on reading the contents of `/proc/self/cmdline` when running on Linux. This has no effect on the vast majority of executables, but most of the Swift toolchain and any command line tools built with Swift misbehave badly. See [the bug filed against Docker][dockerbug] and [the affected CommandLine logic][cmdlinefail] for further detail.

It's not clear (at least not to me) whether `/proc/<pid>/cmdline` should be considered canonical. However, the discussion on [the `proc(5)` manpage][proc5man] does suggest to me that it should not - specifically this part:

```
              If, after an execve(2), the process modifies its argv
              strings, those changes will show up here.  This is not the
              same thing as modifying the argv array.

              Furthermore, a process may change the memory location that
              this file refers via prctl(2) operations such as
              PR_SET_MM_ARG_START.

              Think of this file as the command line that the process
              wants you to see.
```

(I acknowledge that, as @belkadan pointed out to me, there doesn't seem to be any alternative solution at all for shared libraries, but I'd argue that it'd be better for only executables to do it "right" than for nothing to do so.)

**Steps to reproduce**
[See upstream (downstream?) bug][dockerbug]

**Expected behavior**
[See upstream (downstream?) bug][dockerbug]

**Environment**
[See upstream (downstream?) bug][dockerbug]

[dockerbug]: https://github.com/docker/for-mac/issues/7058
[cmdlinefail]: https://github.com/apple/swift/blob/main/stdlib/public/CommandLineSupport/CommandLine.cpp#L175-L199
[proc5man]: https://man7.org/linux/man-pages/man5/proc.5.html#:~:text=enabled.-,%2Fproc%2Fpid%2Fcmdline,you%20to%20see.

**Comment by gwynne** [comment] 2023-11-20 17:29
Additional info:

[Here is the workaround I've been using](https://gist.github.com/gwynne/c005b7740cb28d01cf1f25e58e26eb25) with Intel Docker containers. Can be applied trivially to a `swift:jammy` image (all dependencies are already available). Tested only on Ubuntu Jammy so far. Works with 100% reliability (except with executables linked with `--static-swift-stdlib`) and to date there have been no observed side effects (not even any performance penalty).

(This is obviously not a good long-term solution; I don't intend it as such.)

**Comment by hactar** [comment] 2024-01-07 18:18
If I'm not mistaken this causes the `error: Unexpected argument '/usr/bin/swift-build'` error when trying to run `swift build` - and the `error: invalid driver name: swift-driver` when running `swift` - or at least I can make these errors go away if I turn off Rosetta emulation in Docker.

**Comment by gwynne** [comment] 2024-01-07 20:38
Yes, this is the cause of that error.

**Comment by al45tair** [comment] 2024-02-13 17:10
So, yes, `/proc/self/cmdline` _is_ canonical, in that it retrieves data from the region in the process's initial stack where the kernel originally stashed the command line arguments. The problem here is that the way `binfmt_misc` works is that it starts qemu or Rosetta as the process, and those processes then load and execute the binary they've been told to run under emulation — but that binary is running _in the qemu or Rosetta process_, so if it reads `/proc/self/cmdline`, it sees not the arguments that were passed to its `main()` function, but the ones that were passed to qemu or Rosetta.

**Comment by al45tair** [comment] 2024-02-13 17:21
qemu and Rosetta could fix this problem themselves by calling `prctl(2)` with `PR_SET_MM_ARG_START` and pointing that at the arguments they pass on to the emulated program. That would mean that the emulated program could read `/proc/self/cmdline` and get its arguments, as before. It does have the side-effect of making it so that e.g. `ps` would show only the emulated program, and not the fact that it was running in qemu or Rosetta. However, that would make some sense, given that the emulated program could _itself_ call `prctl(2)` or `setproctitle(3bsd)`, both of which would update the values read from `/proc/self/cmdline`.

**Comment by gwynne** [comment] 2024-02-13 18:27
I think using `/proc/self/cmdline` instead of the `argc`/`argv` provided to `main()` should be treated as a fallback (such as when `dlopen()`ing a library built with Swift) rather than the default behavior. (Same goes for using `_NSGetAgv()` etc. on Darwin, for that matter.)

**Comment by al45tair** [comment] 2024-02-13 18:35
I _might_ have a way to fix this; I'm investigating at the moment — I need to reproduce the problem first, but I think we can do without reading `/proc/self/cmdline`.

**Comment by al45tair** [comment] 2024-02-13 18:38
FWIW, on Darwin or Windows, it's perfectly reasonable to get the command line out-of-band (i.e. without stashing the pointers passed to `main()`). The C standard doesn't say this is possible, but both of those platforms provide APIs to allow for it.

**Comment by al45tair** [comment] 2024-02-19 11:27
On further investigation, this appears to be a problem with Rosetta itself. We're tracking that with rdar://123115850.

Since it isn't a Swift issue per se (and it also appears to affect some other things too), I'll close this issue — though we may still want to consider not using `/proc/self/cmdline` as a source of argument data.

**Closed by al45tair** 2024-02-19 11:27 UTC
Labels: bug, Linux, standard library, unexpected behavior
