### ISSUE TITLE
No "missing return in instance method" message in function using assert

### ISSUE THREAD

**Issue by thisishusseinali** [apple/swift#61262] opened 2022-09-23 06:24 UTC
**Describe the bug**
**The following function**
```
func useAssert() -> Int {
    print(#function)
    assert(false, "oops")
}
```
compiles successfully in Debug mode.
Only in Release mode is the expected `missing return in instance method expected to return 'Int'` error message generated.

I would have expected the compilation to fail regardless of **Debug/Release** mode settings

**Comment by hamishknight** [comment] 2022-09-23 09:07
Duplicate of #61157

**Closed by hamishknight** 2022-09-23 09:07 UTC
Labels: bug
