### ISSUE TITLE
ClangImporter can cause Swift to abridge Objective-C Protocol definitions depending on link order

### ISSUE THREAD

**Issue by dmaclach** [apple/swift#64158] opened 2023-03-06 23:46 UTC
**Description**
Objective-C protocols are defined in every Objective-C object file that references them. 

For Swift, ClangImporter elides any methods from the protocol that use forward declared types (classes, protocols, enums) and embeds that elided protocol definition into the Swift object files as needed.

If the linker(ld64) finds an abridged "Swift" protocol definition first in the linkage it will use that as the final protocol definition for the final link.

Any code that examines the protocol at runtime using functions like `protocol_copyMethodDescriptionList` will end up examining the abridged protocol and will be missing methods.

A classic example of this is in OCMock (https://github.com/erikdoe/ocmock/blob/master/Source/OCMock/OCProtocolMockObject.m) that needs a full protocol definition to mock protocols correctly.

**Steps to reproduce**
Build and run attached project

**Expected behavior**
Expected:
```
2023-03-06 15:43:41.632110-0800 ProtocolTest[84362:21617038] Protocol: ObjCFileProtocol
2023-03-06 15:43:41.632664-0800 ProtocolTest[84362:21617038] 	aClass : @16@0:8
2023-03-06 15:43:41.632722-0800 ProtocolTest[84362:21617038] 	anEnum : i16@0:8
2023-03-06 15:43:41.632748-0800 ProtocolTest[84362:21617038] 	aProtocol : @16@0:8
2023-03-06 15:43:41.632769-0800 ProtocolTest[84362:21617038] 	getInt : i16@0:8
Program ended with exit code: 0
```

Actual:
```
2023-03-06 15:44:11.235527-0800 ProtocolTest[84446:21619329] Protocol: ObjCFileProtocol
2023-03-06 15:44:11.235958-0800 ProtocolTest[84446:21619329] 	getInt : i16@0:8
Program ended with exit code: 0
```

**Environment**
Xcode 14.2
Build version 14C18

[ProtocolTest.zip](https://github.com/apple/swift/files/10903888/ProtocolTest.zip)

**Comment by allevato** [comment] 2023-03-06 23:51
My guess here (not confirmed though) is that Swift's IRGen is emitting the Obj-C protocol metadata based on the Swift synthesized decl for the protocol, which has dropped anything that's only forward-declared, instead of emitting the metadata based on the _original_ Clang decl that was imported.

@NuriAmari Do you know if SE-0384 and https://github.com/apple/swift/pull/61606 will also fix this odd situation? Can we add a test for it specifically?

**Comment by NuriAmari** [comment] 2023-03-07 00:03
Not sure, I'll have to try it. Might work, but the differences between the synthesized decl and the original Clang decl might still be too great. I'll try it and add a test when I have the time.

**Comment by NuriAmari** [comment] 2023-03-07 18:47
@dmaclach @allevato The provided examples repros for Xcode 14.2, but with newer toolchains downloaded from: https://www.swift.org/download/#snapshots, it seems to be fixed.

**Comment by dmaclach** [comment] 2023-03-07 20:43
@NuriAmari It does appear to be fixed with Xcode 14.3 beta 2

**Comment by allevato** [comment] 2023-03-07 20:50
To close the loop on this, it looks like this was fixed by https://github.com/apple/swift/pull/61750, which is indeed in the 5.8 releases.

**Closed** 2023-03-07 20:51 UTC
Labels: bug, triage needed

**Comment by CrystDragon** [comment] 2024-11-01 10:19
Using Xcode 16.0 to run the test project provided by OP, this problem raises again. @dmaclach @allevato
