### ISSUE TITLE
error: type 'Bundle' has no member 'module'

### ISSUE THREAD

**Issue by SusanDoggie** [apple/swift#63737] opened 2023-02-17 02:05 UTC
**Description**
error: type 'Bundle' has no member 'module'

This error only occurs in swift 5.9-dev

refs: 
https://github.com/apple/swift-source-compat-suite/pull/747
https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/122/artifact/swift-source-compat-suite/FAIL_Doggie_5.7_BuildSwiftPackage.log

**Expected behavior**
Build success

**Environment**
swift 5.9-dev

**Comment by etcwilde** [comment] 2023-04-21 21:46
We're seeing this in the Swift-5.8 source compat suite testing as well: https://ci.swift.org/job/swift-5.8-source-compat-suite/72/.

**Comment by etcwilde** [comment] 2023-04-21 21:53
This is likely an effect of the SDK; https://developer.apple.com/documentation/foundation/bundle
Foundation `bundle` does not a `module` (that I see anyway).

**Comment by SusanDoggie** [comment] 2023-04-22 10:46
> This is likely an effect of the SDK; https://developer.apple.com/documentation/foundation/bundle
> Foundation `Bundle` does not a `module` (that I see anyway).

That’s swift pm resources 
https://developer.apple.com/documentation/xcode/bundling-resources-with-a-swift-package

**Comment by etcwilde** [comment] 2023-04-22 18:58
Okay, just asked @neonichu, `swift build --build-system xcode` builds all of the way through.
Maybe something changed in SwiftPM so it's not detecting what it should do correctly?

**Comment by neonichu** [comment] 2023-04-24 04:07
I see this when building this package:

```
warning: 'doggie': found 10 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/neonacho/Desktop/Doggie/Sources/DoggieGPU/CoreImage/Shaders/WrapTileKernel.metal
    /Users/neonacho/Desktop/Doggie/Sources/DoggieGPU/CoreImage/Shaders/SVGComponentTransferKernel.metal
    /Users/neonacho/Desktop/Doggie/Sources/DoggieGPU/CoreImage/Shaders/PalettizeKernel.metal
    /Users/neonacho/Desktop/Doggie/Sources/DoggieGPU/CoreImage/Shaders/SVGDisplacementMapKernel.metal
    /Users/neonacho/Desktop/Doggie/Sources/DoggieGPU/CoreImage/Shaders/BilateralFilter.metal
    /Users/neonacho/Desktop/Doggie/Sources/DoggieGPU/CoreImage/Shaders/kMeansClusteringKernel.metal
    /Users/neonacho/Desktop/Doggie/Sources/DoggieGPU/CoreImage/Shaders/SVGLightingKernel.metal
    /Users/neonacho/Desktop/Doggie/Sources/DoggieGPU/CoreImage/Shaders/SVGTurbulenceKernel.metal
    /Users/neonacho/Desktop/Doggie/Sources/DoggieGPU/CoreImage/Shaders/SVGConvolveKernel.metal
    /Users/neonacho/Desktop/Doggie/Sources/DoggieGPU/GPContext/MeshGradientKernel.metal
```

which looks expected to me, SwiftPM does not support Metal files, so it will not include them as resources by default. Xcode or `swift build --build-system xcode` support Metal files, so they do include them by default. If there happen to be zero resources in a target, we do not generate the `Bundle.module` accessor for it, so that's likely what is happening here.

There is a slight quirk to this behavior in that SwiftPM 5.4 and earlier had a bug where the resource rules did not differentiate between using SwiftPM's build system and Xcode's build system. We preserve this behavior in packages with that tools-version (see [here](https://github.com/apple/swift-package-manager/blob/38a7d0eef9e167aca3af5ce792fa332571ed747f/Sources/PackageLoading/TargetSourcesBuilder.swift#L127)). Note while you may not receive a compilation error in those older tools-versions, you'll end up with runtime errors because SwiftPM's build system does not know about Metal files and therefore copies them instead of processing them.

**Comment by AnthonyLatsis** [comment] 2023-04-26 14:18
@neonichu Since this is apparently related to SwiftPM and not the compiler, do you mind transferring the issue?

**Closed** 2023-06-02 14:45 UTC
Labels: bug, compiler, regression, transfer candidate, source compatibility suite, swift 5.9, unexpected error

**Comment by tmaly1980** [comment] 2023-06-13 00:11
Is this being addressed somewhere else?

**Comment by brimworks** [comment] 2023-06-22 14:44
I'm also running into this problem. Is this issue being tracked anywhere?

**Comment by neonichu** [comment] 2023-06-22 16:42
This is not an actual issue in SwiftPM. Please file a separate issue with steps to reproduce if you happen to be seeing the same error message due to a different root cause.

(maybe we should consider locking this to avoid drive-by comments, @shahmishal?)
