### ISSUE TITLE
In main.swift, variables can be used before they are declared, leading to undefined behavior

### ISSUE THREAD

**Issue by natinusala** [apple/swift#72894] opened 2024-04-06 20:46 UTC
### Description

In `main.swift`, you can use variables before they are declared, leading to undefined behavior (usually a runtime crash when the variable is used). 

I say `main.swift` because the issue does NOT appear when using `@main`, it only appears if the top-level code is "stray" inside `main.swift`.

I would expect the compiler to fail and tell me that I can't use the variable before its declaration.

### Reproduction

Write this into `main.swift` and call `swift run` :

```swift
print("Begin")
print(foobar)
print("End")

let foobar = "test"
```

Output:
```
Build complete! (1.15s)
Begin

End
```

Notice how the string in the middle is empty when printing it. This code should not compile.

However, this :

```swift
@main
struct Main {
    static func main() {
        print("Begin")
        print(foobar)
        print("End")
    }
}

let foobar = "test"
```

Runs fine:

```
Build complete! (0.78s)
Begin
test
End
```

### Expected behavior

Compilation should fail with an error akin to `error: use of variable 'foobar' before its declaration`

### Environment

Swift version 5.10 (swift-5.10-RELEASE)
Target: x86_64-unknown-windows-msvc

Reproduced on Windows (Swift 5.10) and macOS (Swift 5.9)

**Comment by xavgru12** [comment] 2024-04-13 09:59
This seems to be a bug that could be a good first issue, am I right?

**Comment by AnthonyLatsis** [comment] 2024-04-13 10:16
Duplicate of #70323

**Closed by AnthonyLatsis** 2024-04-13 10:16 UTC
Labels: bug, duplicate, compiler, definite initialization, accepts invalid, SIL, memory safety, swift 6.0, script mode

**Comment by AnthonyLatsis** [comment] 2024-04-13 10:18
> This seems to be a bug that could be a good first issue, am I right?

Old issue that are repeatedly reported are generally not easy to fix, so I doubt so.
