### ISSUE TITLE
In-function variables with property wrappers clash with consecutive statements

### ISSUE THREAD

**Issue by yakovmanshin** [apple/swift#62087] opened 2022-11-13 20:36 UTC
## Description
When a property wrapper is applied to a variable inside a function, the compiler fails to correctly identify the end of the statement.

## Steps to Reproduce
1. Inside a function, declare a variable with a property wrapper applied to it;
2. The value must be provided in the wrapper attribute, not after the variable’s name (see code snippets);
3. On a consecutive line, call a function.

## Code Snippets
```swift
// Error:
func testValue1() {
    @State(initialValue: 123) var state
    
    XCTAssertEqual(state, 123)
}
```

```swift
// Same statement, no error:
func testValue2() {
    @State var state = 123
    
    XCTAssertEqual(state, 123)
}
```

## Expected Behavior
The compiler treats the lines as two separate statements.

## Actual Behavior
The following errors, warnings, and suggested fixes appear in the gutter:
* [E] `Consecutive statements on a line must be separated by ';'` → `Insert ';'` (accepting the fix inserts a semicolon at an unexpected place: `XCTAssertEqual;(state, 123)`)
* [E] `Found an unexpected second identifier in variable declaration; is there an accidental break?` → `Join the identifiers together` (accepting the fix removes the line break, resulting in `@State(initialValue: 123) var stateXCTAssertEqual(state, 123)`)
* [W] `Variable is unused` (no suggested fixes)

## Screenshots
![](https://user-images.githubusercontent.com/4648742/201543326-9a1cd793-36a3-4676-b000-79bbf5c5c246.png)

## Environment
* macOS 13.0.1
* Xcode 14.1

**Comment by yakovmanshin** [comment] 2022-11-13 20:41
The same error occurs with property wrappers which take no external values:

```swift
@propertyWrapper
struct AlwaysTrue {
    var wrappedValue: Bool { true }
}

// Error:
func testValue3() {
    @AlwaysTrue var trueOrFalse
    
    XCTAssertTrue(trueOrFalse)
}
```

Unlike the original example with `@State`, a declaration with `@AlwaysTrue` can’t be rewritten in another way to avoid the error.

**Comment by yakovmanshin** [comment] 2022-11-13 20:42
The fix I found is manually adding a semicolon to the end of the first line:

```swift
func testValue3() {
    @AlwaysTrue var trueOrFalse;
    
    XCTAssertTrue(trueOrFalse)
}
```

**Comment by yakovmanshin** [comment] 2022-11-13 20:52
This issue is not limited to test methods and `XCTest` functions:

```swift
// Error:
func testValue1() {
    @State(initialValue: 123) var state
    
    doSomething()
}
```

However, consecutive lines which start with a keyword (tested with `let`, `var`, `func` (nested functions), `defer`, and `return`) don’t result in the error:
```swift
// No error:
func testValue1() {
    @State(initialValue: 123) var state
    
    let expectedValue = 123
    
    XCTAssertEqual(state, expectedValue)
}
```

**Comment by AnthonyLatsis** [comment] 2022-11-14 04:08
Duplicate of #57542

**Closed by AnthonyLatsis** 2022-11-14 04:08 UTC
Labels: bug, duplicate, parser, compiler, property wrappers
