### ISSUE TITLE
Compiler crash when dump-parse for init in extension declaration context 

### ISSUE THREAD

**Issue by jaesmoke** [apple/swift#61952] opened 2022-11-06 14:35 UTC
The issues seems to be that InitKindRequest attempts to call ExtensionDecl::getExtendedNominal() which at this point is still not bound.

See https://godbolt.org/z/9fchn6TMr

Expected behavior
Not to crash but dump pre type-checked AST

**Comment by AnthonyLatsis** [comment] 2022-11-06 18:19
Duplicate of #61806

**Closed by AnthonyLatsis** 2022-11-06 18:19 UTC
Labels: bug, duplicate, compiler, compiler crash, crash
