### ISSUE TITLE
[Swift 5.9] Using shorthand syntax to reference @MainActor isolated method from non isolated context raises error

### ISSUE THREAD

**Issue by kokluch** [apple/swift#68117] opened 2023-08-24 14:20 UTC
**Description**

Accessing the init method of a @MainActor isolated object to store as a closure raises an isolation error since Swift 5.9.

**Steps to reproduce**

```swift
@MainActor
struct Component {
    init() {}
}

struct Builder<T> {
    private let builder: @MainActor () -> T
    
    init(
        builder: @MainActor @escaping () -> T
    ) {
        self.builder = builder
    }
    
    @MainActor
    func build() -> T {
        builder()
    }
}

let _ = Builder { Component() } // OK
let _ = Builder(builder: Component.init) // KO: Call to main actor-isolated initializer 'init()' in a synchronous nonisolated context
```

**Expected behavior**

I would expect the last line to compile successfully as it used to prior to Swift 5.9

**Environment**
- Swift compiler version info 
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.106 clang-1500.0.40.1)
Target: arm64-apple-macosx13.0
- Xcode version info 
Xcode 15.0
Build version 15A5229h
- Deployment target: 
iOS 15.0

**Comment by skorulis** [comment] 2023-11-03 00:21
A related issue to this is that it's possible to completely bypass the `@MainActor` isolation.

```
@MainActor
struct Component {
    init() {}
}

final class ClosureContainer {
    var foo: (() -> Component)?
    var bar: (() -> Component)?
    
    init() {
        // Store closure in a MainActor context
        Task { @MainActor in
            self.foo = { Component() }
            self.bar = Component.init
        }
    }
    
    // Calling @MainActor isolated initializers in a non isolated context
    func run() {
        _ = foo?()
        _ = bar?()
    }
}
```

**Expected behavior**

It should be a compiler error to store a `@MainActor` closure without the closure being marked `@MainActor`.

** Environment**
Swift compiler version info
swift-driver version: Swift 5.9.2 (5.9.2.2.51)
Target: arm64-apple-macosx13.0
Xcode version info
Xcode 15.1 beta 2
Build version 15C5042i
Deployment target:
iOS 17.2

**Comment by skorulis** [comment] 2023-11-03 00:21
I can replicate the original issue in XCode 15.1 beta 2.

**Comment by loganblevins** [comment] 2024-01-04 21:36
Bumping this issue. Having to find workarounds

**Comment by dfed** [comment] 2024-04-06 07:50
I think this is a duplicate of #67581

**Comment by hborla** [comment] 2024-04-27 05:06
Duplicate of https://github.com/apple/swift/issues/67581

**Closed** 2024-04-27 05:06 UTC
Labels: bug, triage needed
