### ISSUE TITLE
Swift compiler crashing on attached sample project

### ISSUE THREAD

**Issue by schnampcc** [apple/swift#59820] opened 2022-06-30 21:25 UTC
**Describe the bug**
Swift compiler crashes when compiling the attached project 

**To Reproduce**
Attempt to run the attached project in XCode 14 beta 2. Works in version 13.3

**Expected behavior**
Project to compile and launch the sample app

**Environment (please complete the following information):**
 - OS: macOS Monterey 12.4
 - Xcode Version/Tag/Branch: Version 14.0 beta 2 (14A5229c)

**Additional context**
I am able to work around the issue by manually specifying the type of my lazy var as `Test`. 

[Sample.zip](https://github.com/apple/swift/files/9023486/Sample.zip)

**Comment by slavapestov** [comment] 2022-07-02 02:19
@xedin Looks like an issue with multi-statement closures.

**Comment by xedin** [comment] 2022-07-02 02:41
Thank you, @slavapestov! This a dupe of https://github.com/apple/swift/issues/59329 which is fixed in 5.7, tested with the project as well. @schnampcc you should be able to verify using the latest 5.7 snapshot.

**Closed** 2022-07-19 19:24 UTC
Labels: bug
