### ISSUE TITLE
Change "has been removed" to "was removed".

### ISSUE THREAD

**Issue by JessyCatterwaul** [apple/swift#73246] opened 2024-04-25 08:10 UTC
### Motivation

E.g. 

`C-style for statement has been removed in Swift 3`

That implies you're using Swift 3. Nobody is!

### Proposed solution

Either always use "was removed", instead, or automate the conjugation to change.

**Comment by saehejkang** [comment] 2024-04-25 16:01
@AnthonyLatsis getting back into working on the compiler and I would like to be assigned to this

**Comment by saehejkang** [comment] 2024-04-27 06:27
Been a while since I updated my `swift-project` folder and kept my code up to date. Getting some errors after running the following steps in order.

1. `utils/update-checkout`
2. `utils/build-script --swift-darwin-supported-archs "$(uname -m)" --xcode --clean`

Then I just wanted to run the `tests` to make sure everything was working correctly.

`utils/run-test --lit ../llvm-project/llvm/utils/lit/lit.py \
  ../build/Ninja-RelWithDebInfoAssert/swift-macosx-$(uname -m)/test-macosx-$(uname -m)`

Got the following errors below (more than one cmake error)

```
CMake Error in unittests/SourceKit/SwiftLang/CMakeLists.txt:
  Imported target "llvm_gtest_main" includes non-existent path

    "/Users/saehejkang/Documents/swift-project/llvm-project/llvm/utils/unittest/googletest/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

-- Generating done (0.5s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
FAILED: build.ninja 
/opt/homebrew/Cellar/cmake/3.27.4/bin/cmake --regenerate-during-build -S/Users/saehejkang/Documents/swift-project/swift -B/Users/saehejkang/Documents/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64
ninja: error: rebuilding 'build.ninja': subcommand failed
ERROR: command terminated with a non-zero exit status 1, aborting
```

Are there any steps I am missing? Maybe issue is caused by updating xcode and the sdks?

**Comment by AnthonyLatsis** [comment] 2024-04-27 06:54
Have you built the project? The `--xcode` invocation is just for generating Xcode projects, it doesn’t build anything. Don’t waste time running the test suite after a checkout; if the Ninja build succeeds, you’re good to go!

**Comment by saehejkang** [comment] 2024-04-27 08:13
Is this the build command you are talking about? This is also failing with lots of errors in the `MacOSX14.4.sdk` files.
```
utils/build-script --skip-build-benchmarks \
  --skip-ios --skip-watchos --skip-tvos --swift-darwin-supported-archs "$(uname -m)" \
  --sccache --release-debuginfo --swift-disable-dead-stripping \
  --bootstrapping=hosttools
``` 

Also, from when developing a while back, I created an xcode project called `swift-build` that runs the `swift-frontend` target. I used to just run the build, but am getting the error above I posted on the last comment.

**Comment by AnthonyLatsis** [comment] 2024-04-27 09:40
Try a `--clean` build. If that doesn’t work, check your Xcode version per the guide. Swift is dependent on LLVM, but Swift targets do not build their LLVM dependencies — you are supposed to pre-build them using the build script. The more your LLVM build artifacts (`llvm-macosx-<arch>`) fall behind your Swift checkout, the greater the risk that building just (say) `swift-frontend` will fail.

**Comment by saehejkang** [comment] 2024-04-27 19:37
Looks like the command below worked

```
utils/build-script --skip-build-benchmarks \
  --skip-ios --skip-watchos --skip-tvos --swift-darwin-supported-archs "$(uname -m)" \
  --sccache --release-debuginfo --swift-disable-dead-stripping \
  --bootstrapping=hosttools --clean
```

**Closed** 2024-05-17 06:57 UTC
Labels: improvement, parser, compiler, good first issue, diagnostics QoI
