### ISSUE TITLE
Nested type conformance problem

### ISSUE THREAD

**Issue by dabrahams** [apple/swift#59016] opened 2022-05-23 04:09 UTC
With swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: arm64-apple-macosx12.0

```swift
enum S0: Int, Comparable { // compiles fine
  static func < (lhs: Self, rhs: Self) -> Bool { lhs.rawValue < rhs.rawValue }
  case A, B
}

struct Test {
  func test() {
    enum S1: Int, Comparable { // fails
      static func < (lhs: Self, rhs: Self) -> Bool { lhs.rawValue < rhs.rawValue }
      case A, B
    }
  }
}
```

should compile, but yields:

```
x.swift:8:10: error: type 'S1' does not conform to protocol 'Comparable'
    enum S1: Int, Comparable {
         ^
x.swift:8:14: note: enum declares raw type 'Int', preventing synthesized conformance of 'S1' to 'Comparable'
    enum S1: Int, Comparable {
             ^
Swift.FloatingPoint:3:24: note: candidate would match if 'S1' conformed to 'FloatingPoint'
    public static func < (lhs: Self, rhs: Self) -> Bool
                       ^
Swift.BinaryInteger:4:24: note: candidate has non-matching type '<Self, Other> (Self, Other) -> Bool'
    public static func < <Other>(lhs: Self, rhs: Other) -> Bool where Other : BinaryInteger
                       ^
Swift._Pointer:2:24: note: candidate would match if 'S1' conformed to '_Pointer'
    public static func < (lhs: Self, rhs: Self) -> Bool
                       ^
Swift.Strideable:2:35: note: candidate has non-matching type '<Self> (Self, Self) -> Bool'
    @inlinable public static func < (x: Self, y: Self) -> Bool
                                  ^
Swift.StringProtocol:4:35: note: candidate would match if 'S1' conformed to 'StringProtocol'
    @inlinable public static func < <RHS>(lhs: Self, rhs: RHS) -> Bool where RHS : StringProtocol
                                  ^
Swift.Comparable:2:17: note: protocol requires function '<' with type '(S1, S1) -> Bool'
    static func < (lhs: Self, rhs: Self) -> Bool
                ^
```

**Comment by slavapestov** [comment] 2022-05-31 19:11
This is a long-standing bug where local types cannot define operators.

**Comment by slavapestov** [comment] 2022-06-03 01:27
Duplicate of https://github.com/apple/swift/issues/45682.

**Closed by slavapestov** 2022-06-03 01:27 UTC
Labels: bug, compiler, type checker
