### ISSUE TITLE
Compilation error diagnostic missing source & line info

### ISSUE THREAD

**Issue by sebastianv1** [apple/swift#61623] opened 2022-10-18 19:29 UTC
**Describe the bug**
We're witnessing some swift compilation error diagnostics not including line information: `<unknown>:0: error: ...`

In a large project it can be very difficult track down exactly where your compilation error exists and feels like a degraded experience.

**Steps To Reproduce**
1. Insert the following snippet into any project
```swift
let list = [1, 2, 3]
let foo = list.compactMap { item -> Int? in
guard item == 1 else {
    return // offending line
}
return item
```
2. Observe error message `<unknown>:0: error: cannot convert return expression of type '()' to return type 'Int?'`
3. I've attached a sample project as well reproducing the bug. [BugRepro.zip](https://github.com/apple/swift/files/9814453/BugRepro.zip)

**Expected behavior**
Error diagnostic includes `<file-path>:<line>` to see compilation error location.

**Screenshots**

**Environment (please fill out the following information)**
 - OS: macOS 12.6
 - Xcode Version/Tag/Branch: Xcode 14.0.1

**Additional context**

**Comment by AnthonyLatsis** [comment] 2022-10-18 21:38
Duplicate of #59716

**Closed by AnthonyLatsis** 2022-10-18 21:38 UTC
Labels: bug

**Comment by marcelofabri** [comment] 2022-10-24 23:16
Still an issue with Xcode 14.1 RC2

**Comment by AnthonyLatsis** [comment] 2022-10-25 13:06
The fix was not picked over to the release branch. @xedin Can we still do it?

**Comment by xedin** [comment] 2022-10-25 13:11
Unfortunately I don't think so, we cannot guarantee anything that's why we ask to verify against main.
