### ISSUE TITLE
[SR-15709] Overflowing operations on Int8 fail to trap if done as FixedWidthInteger

### ISSUE THREAD

**Issue by saagarjha** [apple/swift#57987] opened 2022-01-09 18:12 UTC
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15709      |
   |Radar             | None         |
   |Original Reporter | @saagarjha      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

<https://swift.godbolt.org/z/Ta35Yn5zf>

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: fc0730224133a7d6c5bdc494ea2b731b

  </details>

**Issue Description:**

Operations that *should* overflow a `Int8` silently return zero if you run them in a context where `Self` is `FixedWidthInteger`. Here's an example:

```swift
protocol Foo {
}

extension Int8: Foo {}

extension FixedWidthInteger {
    var bar: UInt8 {
        return UInt8(self & 0xFF)
    }
}

extension Int8 {
    var baz: UInt8 {
        0
        // Compiler error: integer literal '255' overflows when stored into 'Int8'
        // return UInt8(self & 0xFF)
    }
}

let qux = 1 as Int8

print(qux.bar)
print(qux.baz)
```

This executes and prints 0, but the first operation should have trapped. (In previous versions of Swift, this returned a non-zero value.) The operation is broken, and the compiler throws an error in contexts where it can figure out that there will always be an overflow.

**Comment by AnthonyLatsis** [comment] 2024-02-14 14:15
Duplicate of #42919.

**Closed by AnthonyLatsis** 2024-02-14 14:15 UTC
Labels: bug, standard library, generics, numerics, literals, expressions, unexpected behavior, swift 5.11, integer literals
