### ISSUE TITLE
Program compiles successfully when a class inherits from `@objc protocol` but not from other Objective-C classes

### ISSUE THREAD

**Issue by byohay** [apple/swift#62810] opened 2023-01-03 11:28 UTC
**Description**

The program compiles successfully when a class inherits from `@objc protocol` but not from other Objective-C classes, which contradicts the documentation. This also lead to a few crashes in production (At least that's what I suspect).

**Steps to reproduce**

The following code compiles successfully:

```swift
import Foundation

@objc protocol Foo {	
}


class Bar: Foo {
}
```

Even though it says [here](https://docs.swift.org/swift-book/LanguageGuide/Protocols.html#ID284) that:
`Note that @objc protocols can be adopted only by classes that inherit from Objective-C classes or other @objc classes.`

**Expected behavior**

I expect a compilation error to be emitted so that the documented behavior is enforced. A few of our users experienced crashes, that I believe are caused by fact that the class doesn't inherit from `NSObject`. 

**Environment**
- Swift compiler version info: 
```
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx12.0
```
- Xcode version info: Xcode 14.2, Build version 14C18

**Comment by AnthonyLatsis** [comment] 2023-01-16 10:29
The documentation issue is a duplicate of https://github.com/apple/swift-book/issues/66 (the compiler is correct to accept this code). If you ever come across one of those crashes you mention, please do open a new issue.

@amartini51 Requesting a transfer 🙃

**Comment by amartini51** [comment] 2023-01-17 20:56
I'll just close this, since it's a duplicate of an issue that has already been fixed.  The original was fixed by https://github.com/apple/swift-book/pull/67

**Closed by amartini51** 2023-01-17 20:56 UTC
Labels: bug, transfer candidate
